### ISSUE TITLE
[Bedrockean] Breaking Bedrock - Forge

### ISSUE THREAD

**Issue by DerDerARKmag** [QuantumXenon/origins-plus-plus#103]
**Loader**
Forge or Fabric?
Loader: Forge 
**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 43.1.25
- Origins Version: 1.5.0.6 (because it sayed so on the modpage on coursed Forge)
- Origins++ Version: 1.7.1(modpack compatabilety)
- Pehkui Version: 3.4.2

**Origin**
What origin is causing the problem?
The Beadrockean

**Power**
What power is causing the problem?
breaking Beadrock

**Notes**
Any other information that might be useful
I tried a unenchanted and a enchanted Netherite Pickaxe no one worked

**Comment by QuantumXenon** [comment]
This seems to be a Forge-only issue. I'm not sure how it would be fixed, but it works fine on Fabric. This is probably a bug in the Forge port of Origins, so there isn't really anything I can do about it
