### ISSUE TITLE
Error when joining server : Payload may not be larger than 1048576

### ISSUE THREAD

**Issue by DarkLinkFRYTB** [QuantumXenon/origins-plus-plus#105]
**Loader**
Forge

**Versions**
- Minecraft Version : 1.19.2
- Mod Loader Version : Forge 43.1.55
- Origins Version : origins-forge 1.5.0.6
- Origins++ Version : 1.7.2
- Pehkui Version : 3.6.0

**Origin**
What origin is causing the problem? "Payload may not be larger than 1048576"

**Notes**
Any other information that might be useful
When I remove the mod from server but let it on client, I can join without error but don't have the new origins.

**Comment by QuantumXenon** [comment]
Have you tried [XL Packets Renewed](https://www.curseforge.com/minecraft/mc-mods/xl-packets-renewed)?
