### ISSUE TITLE
Can't dismount from another player as a Binturong while using jockey ability

### ISSUE THREAD

**Issue by F0mu** [QuantumXenon/origins-plus-plus#106]
**Loader**
Forge or Fabric?
Fabric
**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version 0.14.10
- Origins Version 1.7.1
- Origins++ Version 1.7.2
- Pehkui Version 3.6.0

**Origin**
What origin is causing the problem?
Binturong
**Power**
What power is causing the problem?
Jockey
**Notes**
Any other information that might be useful

**Comment by QuantumXenon** [comment]
I have done some testing and I couldn't replicate the issue. 
- Just to confirm, what happens when you press [Shift]?

 It's also possible that I have fixed that since the previous release and forgot (as I tested on the dev version)

**Comment by QuantumXenon** [comment]
I’ll close the issue, and if you still experience the problem in the next version, please let me know
