### ISSUE TITLE
Pehkui

### ISSUE THREAD

**Issue by CloverLeafe** [QuantumXenon/origins-plus-plus#107]
Hello,
I was downloading Origins ++ and when I opened Minecraft is said that I had wrong Pehkui version even though I have just the right version for it. What do I do?
![Screenshot 2022-11-24 114025](https://user-images.githubusercontent.com/118999259/203833101-26198f81-ea8a-4d40-80a1-f827852804bc.png)

**Comment by QuantumXenon** [comment]
Check that you have Pehkui (Forge) installed

**Comment by QuantumXenon** [comment]
Let me know if that hasn't fixed it
