### ISSUE TITLE
Rift Mage's ability "Charon's Boat" does not work.

### ISSUE THREAD

**Issue by Electro0922** [QuantumXenon/origins-plus-plus#108]
**Loader**
Forge or Fabric?
  - Fabric

**Versions**
- Minecraft Version
  - 1.19.2
- Mod Loader Version
  - 0.14.10
- Origins Version
  - 1.7.1
- Origins++ Version
  - 1.7.2
- Pehkui Version
  - 3.6.0

**Origin**
What origin is causing the problem?
  - Rift Mage

**Power**
What power is causing the problem?
  - Charon's Boat

**Notes**
Any other information that might be useful
  - Could be that I do not know how to use it. The description isn't very helpful with this specific ability as it tells me to avoid a fatal blow to activate it. I have tried shielding on half heart, moving out of the way, etc.

**Comment by QuantumXenon** [comment]
Thanks for pointing that out. I fixed the issue a few days ago, so it’ll be put with the next update

**Comment by Electro0922** [comment]
Thanks! Sorry for the bother btw, your mod is wonderful. Appreciate the response
