### ISSUE TITLE
Can't open any worlds

### ISSUE THREAD

**Issue by UnderTracer** [QuantumXenon/origins-plus-plus#109]
I can create the world and play in it just fine the first time, but after I save and exit and try to join back it says "invalid player data"
Any Idea why it happens or any fixes? I will attach the logs if anyone needs it.
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/10092737/latest.log)

**Comment by QuantumXenon** [comment]
Try installing XL Packets

**Comment by QuantumXenon** [comment]
Let me know if that hasn't fixed it
