### ISSUE TITLE
Can't download the fabric version of the mod.

### ISSUE THREAD

**Issue by MemorieBE** [QuantumXenon/origins-plus-plus#111]
**Loader**
Forge or Fabric?: Fabric

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 0.14.10
- Origins Version: 1.7.1
- Origins++ Version: 1.7.2
- Pehkui Version: 3.6.0

**Notes**
When I download the mod, it isn't compatible with fabric and only uses the forge modloader.
Also, the Java app doesn't run neither.

**Comment by QuantumXenon** [comment]
@MemorieBE Just to confirm - are you downloading [this](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus/files/3995401) file and putting it in your mods folder along with [Origins](https://www.curseforge.com/minecraft/mc-mods/origins/files/4044263) and [Pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui/files/4059310)?

**Comment by QuantumXenon** [comment]
Could you please provide an error message/screenshot/logs if that doesn't help?

**Comment by MemorieBE** [comment]
Yes, I downloading from that website.

![Image](https://user-images.githubusercontent.com/58493301/204162389-25542df5-0496-4d51-a3c4-9562ad8d3287.png)

**Comment by QuantumXenon** [comment]
Try going into the CurseForge profile, then click the three dots next to `Play`. Then click `Open Folder` and when that opens in Explorer, open the `mods` folder. Directly drag the .jar file downloaded from CurseForge into that folder.

**Comment by MemorieBE** [comment]
That works! Thank you.
