### ISSUE TITLE
mod file needs language provider javafml:43

### ISSUE THREAD

**Issue by Allalous** [QuantumXenon/origins-plus-plus#113]
I'm trying to make a pack for my friends and I to play and after I added this mod to the pack I get this error.

Mod file origins-plus-plus1.7.2.jar needs language provider javafml:43 or above to load
We have found 40

How do I go about fixing this so we can use your mod in the pack?

**Comment by QuantumXenon** [comment]
This is caused because I have restricted the mod to 1.19.2 (only for Forge) due to a critical bug which prevented keybinds from working in earlier versions
