### ISSUE TITLE
Mod is marked as 1.18.1, 1.18.2, 1.19.1 and 1.19 compatible on CurseForge, but requires 1.19.2 to function

### ISSUE THREAD

**Issue by ChiefArug** [QuantumXenon/origins-plus-plus#117]
As mentioned in https://github.com/QuantumXenon/origins-plus-plus/issues/113 the mod requires 1.19.2 forge to function, however its files are marked as compatible with 1.18.1, 1.18.2, 1.19.1 and 1.19 on CurseForge.
![image](https://user-images.githubusercontent.com/73862885/206890470-530a35dd-493d-4bb8-8792-86a9f234fccb.png)
This is causing confusion for users, as it appears when they search for Forge 1.18.2 origins addons, but then they install it and it causes the game to crash.

You can click on a files name in CurseForge, then on the edit button to change the versions it is compatible with.

**Comment by QuantumXenon** [comment]
Yes, sorry about this. The issue is that it's compatible with Fabric for those versions. I plan to split the Forge and Fabric versions on CurseForge for the next release to make this clearer and so that the dependencies can be properly marked.
