### ISSUE TITLE
1.19.2 sometimes fail load

### ISSUE THREAD

**Issue by Joshernoob** [QuantumXenon/origins-plus-plus#118]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?
Forge
**Versions**
- Minecraft Version- 1.19.2
- Mod Loader Version-43.2.0
- Origins Version-1.5.0.6 and down
- Origins++ Version-1.7.2 and down
- Pehkui Version-3.6.0 and down

**Origin**
N/A

**Power**
N/A

**Notes**
When loading in world (single player) even with just base mods Origins, Origins++ and Pehkui and/or added mods there about a 50/50 chance that get a invaid player error or can't find origin/origins erorr or can't find root error then crash, to see these you do have to make world back to back but the errors gets worse on servers and error out same way with the existing world and even crash if you try to get back in

**Comment by QuantumXenon** [comment]
Yeah - I've noticed this too. I'm not 100% sure what is causing it, but I think it might be a bug with Origins (Forge). There isn't anything that I can do (that I'm aware of) to help with this
