### ISSUE TITLE
A number of Black Mage's secret spells don't work/do nothing

### ISSUE THREAD

**Issue by joemama098463** [QuantumXenon/origins-plus-plus#122]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft 1.19.2
- Forge 1.19.2 43.2
- Origins 1.5.0.6
- Origins++ 1.7.2
- Pehkui Version 3.6.1

**Origin**
Black Mage

**Power**
Explosion power: shift+g does nothing with gunpowder in offhand
Ultimate Abilities: g and h do nothing with dragon head in offhand

**Notes**
managed to fix that weird "cursedforge mods doing nothing" bug, turns out I had a 9minecraft mod hidden in the .minecraft folder which broke everything not 9minecraft. 

tested after using the Orb of Origin multiple times for 2 consecutive hours

**Comment by joemama098463** [comment]
*notes:
-after further testing black mage's default shift+g attack does not trigger unless a "mage book" has been made
-issues persist in worlds with no Orb of Origin ever used
-shift+g attack does not function with phantom membrane in offhand
-shift+g attack does not work with netherite pickaxe in offhand

**Comment by QuantumXenon** [comment]
Thanks for the report! I’ve fixed this issue since the last release, but haven’t yet released the new version

**Comment by joemama098463** [comment]
oh, thanks
