### ISSUE TITLE
Lost Draconian is Overpowered, Warper Needs More Warp, Shadow Could Use Some Nightvision, End Mage Could Use Partial Nerf

### ISSUE THREAD

**Issue by joemama098463** [QuantumXenon/origins-plus-plus#123]
**Origin**
Lost Draconian, End Mage, Shadow, and Warper

**Rebalances**
Lost Draconian's ability to just spawn with the best melee and defense weapons in the game makes the ENTIRE early and midgame trivial, and while yes you CAN just throw them away but the "don't use it" argument could be said for literally anything. I would recommend either a complete removal of this feature or give them to the player with severely damaged durability (like 5-15% remaining) and the ability to lose said durability so the player still gets an early boost but not one so substantial that it trivializes 60% of the entire game. It also kinda works in lore if you say the weapons are powerful but R E A L L Y old.

Although it's not much of a "balance" change I would say warper's, ya know, warping should feel good to use since its the entire point. At the moment the X teleport does not make a sound or an effect and even something as small as 12 particles and stock sfx would make worlds of difference, I also believe to better fit warper's general vibe of tele-spam the X ability cooldown should be replaced to roughly 5-10 seconds and limit its range to around 10-30 blocks, this way warper can act as the Touhou protagonist with 1 health but unlimited mobility it was always meant to be.

End Mage tends to lean more heavily into physical weapons rather than magic, unlike Black Mage, but despite this also has a default attack spell (h) that is better in every way than Black Mage's default attack spell. It can incapacitate enemies, has bigger AOE, and lower cooldown whereas Black Mage's only inflicts fatigue. I propose a rework of End Mage's H attack, where instead of it dealing large damage and floating enemies into the air as an AOE, it only deals 5 damage in a single projectile, much like the shulker's floaty-orb-thing. This way End Mage does not have such an advantage where it should not really have one over the other mage origins.

The Shadow origin feels great and are fun to play as but generally lacks an extremely important facet of playing as the nighttime class: being able to see. Now, I'm not talking about full on night-vision II, I mean something feint, like a small ring of seeable environment around the character when in near-total darkness. This way the Origin don't contradict its purpose as "the edgy darkness character" by not being able to see where it's dark, unlike its cousin, Shadow-Walker.

**Comment by QuantumXenon** [comment]
I'll do some testing, and if all is well I'll release with the current changes

**Comment by QuantumXenon** [comment]
Also, thanks for all the detailed feedback!
