### ISSUE TITLE
Game believes you are riding something (when you aren't)

### ISSUE THREAD

**Issue by Rayray0011** [QuantumXenon/origins-plus-plus#124]
**Loader**
Forge

**Versions**
- Minecraft 1.19.2
- Forge 43.2.0
- Origins 1.5.0.6
- Origins++ 1.7.2
- Pehkui 3.6.1

**Origin**
Mouse, however, I am unsure if the issue continues with other small origins.

**Power**
It's not a power, but the ability to ride other entities. 

**Notes**
This is basically just the story of what happened. Upon riding a chicken as the mouse origin, I believe the chicken may have died from fall damage, although Minecraft did not seem to register it. I believe this to be the case as the chicken would allow me to control it (move around) but lost its wing-flapping animation and legs. From here, I was unable to dismount the chicken but could mount other entities, such as dogs and cows (confused the game into taming a dog by doing so). I kept the same speed and slow-falling that the chicken gave me upon riding it, but also took fall damage if I dropped by a block. 
After reconnecting to the server, the chicken was gone, but my character's speed was much slower, I couldn't jump up blocks (as if I was still riding the chicken), and I would still take fall damage from dropping small heights. 
The only fix I have found to this is summoning the Orb of Origin and changing my origin (even just reselecting the mouse origin did the trick). However, this would only work until I re-joined the server, forcing me to rinse and repeat.
Attempting to ride ANY other entity (player or otherwise) forces my character to get stuck riding the entity until I re-join, thus needing me to use the Orb of Origin to fix it again. 

I find this mildly inconvenient and would love to hear if I've just overlooked something. Thank you so much for any help you can provide.

**Comment by Rayray0011** [comment]
Just experimented some more with the bug. If the animal carries me away from where I mounted them and I disconnect, I will load in where I originally mounted it upon re-joining.

**Comment by QuantumXenon** [comment]
> **Notes** This is basically just the story of what happened. Upon riding a chicken as the mouse origin, I believe the chicken may have died from fall damage, although Minecraft did not seem to register it. I believe this to be the case as the chicken would allow me to control it (move around) but lost its wing-flapping animation and legs. From here, I was unable to dismount the chicken but could mount other entities, such as dogs and cows (confused the game into taming a dog by doing so). I kept the same speed and slow-falling that the chicken gave me upon riding it, but also took fall damage if I dropped by a block. After reconnecting to the server, the chicken was gone, but my character's speed was much slower, I couldn't jump up blocks (as if I was still riding the chicken), and I would still take fall damage from dropping small heights. The only fix I have found to this is summoning the Orb of Origin and changing my origin (even just reselecting the mouse origin did the trick). However, this would only work until I re-joined the server, forcing me to rinse and repeat. Attempting to ride ANY other entity (player or otherwise) forces my character to get stuck riding the entity until I re-join, thus needing me to use the Orb of Origin to fix it again.

I have done some initial testing in Fabric and all seems fine, I'll have a look at the Forge version later in case it is being caused by Origins (Forge). In the meantime, I don't really know what you can do to avoid this.

**Comment by QuantumXenon** [comment]
Yeah, this looks to be an issue caused by Origins (Forge). Unfortunately, there isn't really anything I can do about this
