### ISSUE TITLE
[Lepus] Crafting

### ISSUE THREAD

**Issue by FeNebron** [QuantumXenon/origins-plus-plus#126]
**Loader**
 - Fabric

**Versions**
- Minecraft 1.19.2
- Fabric-api-0.68.0+1.19.2
- Origins-1.19.2-1.7.1
- Origins-plus-plus-1.7.2
- Pehkui-3.6.0+1.14.4-1.19.3

**Origin**
What origin is causing the problem? - Lepus origin causing the issue

**Notes**
Hey there, I am facing an issue with Lepus origin in origin++.
Description for the issue:
Everytime I craft a tool or weapon (craftings I tried: longsword, pickaxe, axe, shovel, sword), the materials are not used up and stay in the crafting table.
This preserves materials and allows duplication, especially of tools.
I noticed that it happens mostly with tools and weapons. When I crafted shears, bucket or blocks (e.g. diamond block) it didn't happen.

My other observation is that when I crafted these items, they are only basic items and cannot get common, uncommon, rare, epic or legendary traits.
Because of the possibility of duplication and the loss of traits, I think it's a bug. I hope I gave you all the information.
In the future I'll make some more test and experimenting to give you more information about it and maybe I can help you to identify it more.

Thank you for your work :)

**Comment by FeNebron** [comment]
P.S.
I tried these crafts on server and in singleplayer.

**Comment by FeNebron** [comment]
P.S.2.
Sorry, I forgot to mention that I am using Origins++ in Medieval MC Fabric MMC1.

**Comment by QuantumXenon** [comment]
I’m not sure why using Origins++ would break recipes from other mods. Do you still experience the problem if you remove Origins++?

**Comment by FeNebron** [comment]
Right now we are playing without the Origins++ mod and I didn't encounter this problem.
I haven't noticed any similar with other origins when I am using Origins++.
I made a few seconds video about it: https://files.fm/f/hzqwshtr9
Let me know if you prefer a different sharing method or website and I will forward it there. (I cannot upload here because the limit is 10mb)

**Comment by QuantumXenon** [comment]
I've seen your video, but I haven't been able to replicate the issue. Perhaps it has something to do with the crafting table display mod you're using and packets being filled a bit by Origins++. You could try installing XL Packets and Connectivity (if you haven't already)
