### ISSUE TITLE
I'm not sure of the specific issue but the forge version of this mod has stopped functioning

### ISSUE THREAD

**Issue by YeetiumTypeZ** [QuantumXenon/origins-plus-plus#127]
**Loader**
Forge

- Minecraft Version: 1.19.2
forge 43.2.0
origins++ 1.7.2
origins  1.19.2-1.5.0.6

I hope all this info is right and I'm sorry if its not
I apologize I don't know most of this information but the only note I got was that Apoli was not installed but I couldn't find that on curseforge
sorry if it is a stupid issue and I just couldn't notice the obvious.

**Comment by YeetiumTypeZ** [comment]
3 more things
the actual issue is that pre made or new worlds wont load 
the problems stops when i remove the origins++ mod
the code i got is. Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root/apoli:configured_power] was missing.

**Comment by miniscule-minecrafter** [comment]
It's not just you, I've been dealing with the same code response when joining pre-made worlds. Recently added XL Packets (Renewed) and, while it still occasionally crashes, it is less frequent and the origins function well for the most part.

**Comment by QuantumXenon** [comment]
> 3 more things
> the actual issue is that pre made or new worlds wont load
> the problems stops when i remove the origins++ mod
> the code i got is. Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root/apoli:configured_power] was missing.

I’m not sure what causes this, but I think it’s a bug with how Origins (Forge) handles addons

**Comment by YeetiumTypeZ** [comment]
> 

I tried this you you think there may be any other way to fix it

**Comment by QuantumXenon** [comment]
> I tried this you you think there may be any other way to fix it

Is this in relation to the issue of Apoli not being registered as installed?

**Comment by YeetiumTypeZ** [comment]
Sorry I replied to the wrong thing 
What I meant was that deleting and reinstalling did nothing

**Comment by QuantumXenon** [comment]
Have you resolved the issue with Apoli?
