### ISSUE TITLE
[Warden] Limited Vision

### ISSUE THREAD

**Issue by Niko1293** [QuantumXenon/origins-plus-plus#128]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric? 
forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version currently up to date version (not sure where to get it)
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?
Warden 
**Power**
What power is causing the problem?

**Notes**
Any other information that might be useful
 upon launching the world it  freezes up and gives "invalid player data 90% of the time cant even use this mod)
if not that the warden (while the blindness makes sense the   broken looking textures do not)

**Comment by QuantumXenon** [comment]
- To fix the "Invalid Player Data", try installing [XL Packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets), and if that doesn't work, [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) too.
- For the Warden textures, does it look similar to this?
![image](https://user-images.githubusercontent.com/103604117/211073438-40ed7e84-3d44-495b-b69d-b75ec963be5e.png)

**Comment by Niko1293** [comment]
first  just tried the connectivity  didn't work and i've got bothj xl and that installed it still refuses to work,

as for the vision yes that is what is seen,  i know the warden is blind but thats confusing.

**Comment by QuantumXenon** [comment]
I’m not sure what else you can do to fix Invalid Player Data. I’ve seen a couple people fix it my deleting the config for Origins (Forge), so maybe that’ll work for you too?
