### ISSUE TITLE
[Enigma] Balances and Fixes

### ISSUE THREAD

**Issue by miniscule-minecrafter** [QuantumXenon/origins-plus-plus#129]
**Origin**
Enigma

I tested only in single player, so I'll just list the things I noticed.

* The clone ability is a bit finnicky when it comes to remaining visible after use.
Sometimes the clone will appear, sometimes it won't (usually this is determined for the duration of the play session).
 It is either always working or always invisible which probably shouldn't be happening.
 The purple bar still works fine regarding the cooldown though.

* As for the teleportation ability, it uses the primary hot key which is shared with the permeation ability. (G)
This causes some ability mishaps. Sometimes I want to teleport 
and sometimes I want to permeate but it happens at the same time a lot since they use the same ability key. :/

* The ability to hold shift and see players through walls hasn't been tested since this is only through single player testing, so I don't know if it works or not.

* Trying to teleport in water doesn't work.

* The ability to not use weapons strictly says no swords or axes, but you actually can't hit targets with **any** tool
 (pickaxes, hoes, etc.). Not sure if this is how the ability is supposed to work or if its working fine but I'll leave it here anyways.

**Some combination glitches:**
* You can kill your clone (when it works) with a death stare causing invisibility to remain, which ensures perma-invisibility unless you take damage (kinda broken)
* Summoning a clone while permeating through blocks causes trippy lag glitches which vary with each attempt whether intentional or accidental

**Balance Suggestions:**
"Do you have any ideas about how it could be balanced?"

* Since absolutely **no** tools besides your fists can be used to damage entities, it would be nice if the death stare took a little less time to kill. The average time it takes to kill something is around 16-17 seconds (I timed with a stop watch). That's a lot of time to stare at someone's hit box for only one death, especially if there are several people. That could take minutes if you were lucky enough to not lose sight of their hit box. 
* If you lose track of their hit box for even a **moment**, you'll have to stare at them for a renewed duration. 
However, at that point you're either too far away for the ability to activate or they're in an environment with plenty of cover. 
Since this is the enigma's **only** real way to fight without outside assistance and the range of the ability is not that far for long ranged staring contests, you're kinda screwed if you're in the wrong environment or stink at tracking someone's hitbox. 

(Sorry for the wall of text)

* There are some remedies to these points though since the Enigma's kit is all about maneuverability and staying out of sight (and scaring the crap out of people), so you can position yourself into a good spot before looking for trouble and the abilities also act as an excellent way to flee when shi**z** hits the fan. (In short, take the two paragraphs above with a grain of salt)

**Summary:**
Being able to kill someone by looking at them is an **insane** ability and feels awesome to play when done right! The biggest gripe is that the primary ability relies on the target to not move much, stay within range **and** stay exposed. Unless you actively play with hit boxes on, it can also be difficult to determine where to look especially when trying to go long-ranged.

**A couple of little things I noticed and appreciate:** 

* The staring ability works through windows which is really cool!
* Night vision is an excellent little quality of life thing that adds to the flavor of the origin and it gives a sense of advantage in certain environments, super awesome.
* Having the capability to destroy dropped items with your ability is insane and surprisingly empowering. Since dropped items have a hit box, anything including bedrock and netherite items can be destroyed in this way and it adds an extra unique skill to the enigma's niche move set (not sure if this perk was intentional, but it's really cool).

That's about it! Thanks for reading all my stuff and hopefully some of it can be of help .w.

Or skipping to the end, I see you too :) 
Have a survivable day!

**Comment by miniscule-minecrafter** [comment]
Oh, and also! This was done in Forge :)

**Comment by QuantumXenon** [comment]
> * As for the teleportation ability, it uses the primary hot key which is shared with the permeation ability. (G)
>   This causes some ability mishaps. Sometimes I want to teleport and sometimes I want to permeate but it happens at the same time a lot since they use the same ability key. :/

The issue with the powers sharing the same keybind is due to Origins (Forge)

Other than that I've made the changes so they'll be out in the next version
