### ISSUE TITLE
Black Mage Missing spell

### ISSUE THREAD

**Issue by Nemaphius** [QuantumXenon/origins-plus-plus#130]
**Loader**
Both

**Versions**
- Minecraft Version \1.19.2/
- Mod Loader Version \Fabric/
- Origins Version \1.7.1/
- Origins++ Version \1.7.2/
- Pehkui Version \3.5.0/

**Origin**
Black Mage

**Power**
eleventh hidden spell "explosion"

**Notes**
Power is confusing to read in book, pressing normal ability keys doesn't do anything. When looking in files cannot find the spell "Explosion". Btw mana regen is much slower compared to the white mage while the white mage has stronger powers in general (good guys always win huh?).

**Comment by Nemaphius** [comment]
oh btw i was unable to activate the primary for the ultimate ability either

**Comment by QuantumXenon** [comment]
I’ve made changes since the release of 1.7.2 for most of these issues, but I’ll check the mana and power comparison for the mages.

**Comment by Nemaphius** [comment]
Wasn't able to get the shatter spell to work either, not sure if its result of me not knowing how its supposed to work though.

**Comment by Nemaphius** [comment]
Thanks tho, when do you plan on getting the update out? but lots of thanks.

**Comment by QuantumXenon** [comment]
> Thanks tho, when do you plan on getting the update out? but lots of thanks.

I'm hoping to soon, but it's taking a while to test all the changes

**Comment by QuantumXenon** [comment]
> Wasn't able to get the shatter spell to work either, not sure if its result of me not knowing how its supposed to work though.

This will also be fixed in the next version

**Comment by Nemaphius** [comment]
Alright thanks. Btw I can playtest if you need it.
