### ISSUE TITLE
blazian: mobs are hostile in the nether

### ISSUE THREAD

**Issue by Uhntil** [QuantumXenon/origins-plus-plus#131]
Loader: Fabric 0.14.12

Versions: Origins 1.7.1, Origins++ 1.7.2, Pehkui 3.6.3

Origin: Blazian

Power: No Place Like Home: When in the Nether you have Speed II, Strength, and no mobs will attack you.

In my server using the same origins versions, blazian while in the nether has mobs attacking me, strength and speed 2 are applied perfectly, but mobs are attacking, the piglins seem to be passive yet unpassive at the same time, making grunting and aggro noises yet not attacking as if its fighting its natural aggro state, same thing for skeletons but skeletons still shoot, piglin brutes seem to also just attack normally, is there any fix?

**Comment by QuantumXenon** [comment]
This should be fixed in the next version
