### ISSUE TITLE
Can't read origin description.

### ISSUE THREAD

**Issue by Deathwarp6** [QuantumXenon/origins-plus-plus#133]
Forge 43.2.3

MC: 1.19.2
Pehkui: 3.6.3
Origins: 1.5.0.6
Origins ++: 1.7.2

Origins in the GUI have no description, excluding the base description. It is not impossible to play but hard for my friend who is new to the mod. Help would be appreciated, and I apologize ahead of time for the stupidity on my part. It is not a resource pack issue.

![2023-01-22_13 19 11](https://user-images.githubusercontent.com/123326624/213935674-6708f8b4-9436-472b-94f6-6606dbd0c5b4.png)

**Comment by QuantumXenon** [comment]
I’m not sure what would cause that. I’ve only seen it reported a couple times before and didn’t hear of an outcome

**Comment by Deathwarp6** [comment]
I have both installed, I will have to look through my mods and see what may be causing the issue. I appreciate the help though.

**Comment by LichDrifter** [comment]
> I have both installed, I will have to look through my mods and see what may be causing the issue. I appreciate the help though.

Hey man, i had the same problem in my modpack, after testing every mod i found out that it was the journey map mod, if you have it in your modpack switch to Xaero's minimap and it'll work just fine, at least worked for me

**Comment by QuantumXenon** [comment]
@LichDrifter I'm not sure why that would have been a problem, but great that you've found a solution. 

@Deathwarp6 If you've already got those, I have no idea what would be causing the problem. It seems to be related to Origins (Forge) though, so there isn't really anything I can do

**Comment by Deathwarp6** [comment]
I think it is the Forge version, thanks for the help though. I have both already.

**Comment by Deathwarp6** [comment]
Last comment: it is somehow caused by being the only player on the server. Don't know why.

**Comment by QuantumXenon** [comment]
That’s quite strange. I don’t know why that would be

**Comment by Deathwarp6** [comment]
Sorry, that's not helpful, but all I know is if someone else was on I could read it.
