### ISSUE TITLE
Is there a way to disable all origins except for a few?

### ISSUE THREAD

**Issue by TheAyes** [QuantumXenon/origins-plus-plus#134]
Well the players on my server are annoyed at how many origins there are and that it takes way too long to decide. So I wanna disable some except for a few 20'ish or so.
Is this possible?

**Comment by QuantumXenon** [comment]
If you’re on Fabric and 1.19+, there’s a config file called `origins-server.json` in which you can toggle origins and even individual powers.

**Comment by TheAyes** [comment]
That works.
