### ISSUE TITLE
Mod doesn't hard depend on any packet expanding mods.

### ISSUE THREAD

**Issue by ChiefArug** [QuantumXenon/origins-plus-plus#135]
**Loader**
Both

**Versions**
- All
- 
Please make the dependency on XLPackets a hard dependency, its very confusing for users trying to play with this mod but not being able to because of some error like 'invalid player data' or even 'disconnected from server' in one case (in singleplayer..), which isn't helpful at all. A startup error of a mod not being installed is much nicer.

Alternatively, some sort of warning BEFORE trying to join a world/server, if a packet expanding mod isn't present.

(Context: I help out in the CurseForge discord reading logs and crash reports for people. We have been consistently getting problems caused by this mod and XLPackets not being installed)

**Comment by QuantumXenon** [comment]
Sorry about that. I’ve also been getting a lot of reports. I’ve already added the dependency in the mod files, but I haven’t yet released the update as I am in the process of checking for bugs.
