### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by Rogenar** [QuantumXenon/origins-plus-plus#138]
![s1](https://user-images.githubusercontent.com/122460325/215365310-0aa20931-6122-4360-9267-6a0971a17e2f.png)
I get invalid player data error when creating a new world in origins-plus plus-2.0

**Comment by QuantumXenon** [comment]
Have you got XL Packets and Connectivity installed?

**Comment by AspenCypress** [comment]
I've also got this issue but on 1.19.2

**Comment by MrBOOMberMAN** [comment]
Same to me I have conectivity and xl packets and once i create a new world the screen spashes appearing a message, literaly says: Invalid Player data

**Comment by QuantumXenon** [comment]
@MrBOOMberMAN @AspenCypress @Rogenar Are you using Fabric or Forge?

**Comment by Rogenar** [comment]
Fabric versiyon.

**Comment by QuantumXenon** [comment]
I don’t know if it would help, but you could try deleting the origins config (`origins_server.json`) as it might have something to do with a lot of powers being renamed/changed

**Comment by Rogenar** [comment]
I did what you said but still faced the same problem.

**Comment by QuantumXenon** [comment]
Hmm, I don’t know why that would be happening then. When I was testing it before release I didn’t have that issue, but I’ll have another look as it seems to be occurring quite a bit

**Comment by MrBOOMberMAN** [comment]
> @MrBOOMberMAN @AspenCypress @Rogenar Are you using Fabric or Forge?

I Have forge

**Comment by 2el222** [comment]
Happens to me too forge 1.19.2

**Comment by 2el222** [comment]
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/10557860/latest.log)

**Comment by Rogenar** [comment]
ok problem solved. extra thicc packets fabric mod is required. now i was able to create my world and 115 classes appeared.

**Comment by AspenCypress** [comment]
The fix @Rogenar offered works for single player worlds only.
Even paired with connectivity, I am unable to use the modpack within my server.

**Comment by Rogenar** [comment]
Install thicc packets fabric mod on your server then it will be fixed. @AspenCypress

**Comment by AspenCypress** [comment]
@Rogenar That's what I just said in the edit.

**Comment by MrBOOMberMAN** [comment]
and for forge?

**Comment by Rogenar** [comment]
forge versiyon [https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler-](https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge)

**Comment by MrBOOMberMAN** [comment]
> forge versiyon [https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler-](https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler-forge)

Okay I tried , thanks
