### ISSUE TITLE
KEEP SAYS "INVALID PLAYER DATA" WHEN CREATE NEW WORLD

### ISSUE THREAD

**Issue by MrBOOMberMAN** [QuantumXenon/origins-plus-plus#141]
DESCRIPTION:
I can start the game but once i create a new world the screen splash a text: "Invalid Player Data"

MODLOADER:
- FORGE

VERSIONS:
- Minecraft 1.19.2
- Forge 43.2.4
- Origins 1.5.0.6
- Origins++ 1.7.2
- Pehkui 3.6.3

[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/10608528/latest.log)

**Comment by QuantumXenon** [comment]
I assume you've tried XL Packets/Connectivity/Packet Size Doubler?

**Comment by MrBOOMberMAN** [comment]
I Have no idea what is the problem , I tried all but with no results but 
I check the actually the problems with XL PACKETS mod in Github and seems like 
the most of the people are experiencing problems with mods that requires this mod

**Comment by QuantumXenon** [comment]
I'm going to close this issue as there's nothing I can do about it at the moment, and it is not directly related to the mod (as it is an issue with how it is handled as an addon).

I'm aware that it's frustrating that it doesn't work, but I don't know what else to suggest.

**Comment by MrBOOMberMAN** [comment]
okay no problem , probably in future updates the mod will work perfectly
