### ISSUE TITLE
[Child of Cthulhu] Size Change

### ISSUE THREAD

**Issue by flamma71** [QuantumXenon/origins-plus-plus#142]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?

**Power**
What power is causing the problem?

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
@ShuSquyd What bug are you experiencing if you are able to change your size?

**Comment by ShuSquyd** [comment]
Oh sorry I didn't see I write "can"  instead of "can't", my bad ^^'

**Comment by QuantumXenon** [comment]
@ShuSquyd @flamma71 Could you provide some more details? I just tried it now and it works as expected for me.

When I press `G`, I cycle from Normal -> Small ->  Big -> Normal

**Comment by flamma71** [comment]
Strangely I tried this on single player then went to a server and it
started working but I haven’t tested it yet on the single player again it
might be because of some of the other mods and their versions however I
think the issue was fixed. Besides if it works for you guys and it doesn’t
work for me just in single player then that’s fine I only do tests for
builds and such in single player

**Comment by ShuSquyd** [comment]
So I change the keybind and it's work, maybe a issu with a mod of mine (Origins Extra Keybinds maybe?) ^^

**Comment by QuantumXenon** [comment]
Ok, great that the issues seem to be fixed.

**Comment by QuantumXenon** [comment]
#145

**Comment by rwange1** [comment]
I have the same issue in singleplayer, I tried to change keysbinds, but only the dash work.
I use Fabric In 1.19.2
Origins 1.7.1
Origins++ : 2.1.1
Pehkui : 3.7.7+1.19.2
If you have any idea of why it's happening
