### ISSUE TITLE
Origins abilities are all binded to one key in v2.0 forge version

### ISSUE THREAD

**Issue by Cloneus** [QuantumXenon/origins-plus-plus#144]
Also if there is a fix to this, there is no explanation for this anywhere in the mod description.

**Comment by QuantumXenon** [comment]
Are you on Forge 1.18.2?

**Comment by Cloneus** [comment]
Yes, Forge version 40.2.0 as well.

**Comment by QuantumXenon** [comment]
Ah, that’s a bug with Origins (Forge) then. You would have to update to 1.19.2 and 1.5.0.6 to fix it.
