### ISSUE TITLE
[Shadow] Particles

### ISSUE THREAD

**Issue by hubertblain** [QuantumXenon/origins-plus-plus#145]
![fuck me i guess](https://user-images.githubusercontent.com/124746502/217398864-91537825-4f48-4d7c-a9b7-56c4e95748a0.png)

**Loader**
 Fabric

**Versions**
- Origins++ Version

**Origin**
Shadow

**Power**
It's not the power so much as a passive. The particle effects on the shadow are like SUPER blinding and I was hoping you could tone them down a bit, I've been wanting particle effects on it for a while but they are just so blinding. Like i mentioned on the mods comment section in curseforge, the effects are so incredibly abundant it is borderline impossible to see. I have to run off my particle effects just to see which really sucks cause i love being able to see me in my shadow form. now i don't wanna push my luck but it would be AWESOME if the shadow was like the shadow crawler origin, by that, I mean maybe a little darker and transparent with the little ash particle effects. BUTTTTT again i don't wanna push my luck was just hoping you could fix the shadow at least LOVE YOU :D

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
I've also just added particles for the Shadow Crawler too

**Comment by hubertblain** [comment]
Thank you so much for everything you're amazing :D ❤️
