### ISSUE TITLE
[Lepus] Leap + Bunny Hop

### ISSUE THREAD

**Issue by jonask028** [QuantumXenon/origins-plus-plus#147]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*
yup
**Loader**
Quilt

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version:0.17.11
- Origins Version 1.7.1
- Origins++ Version 2.0
- Pehkui Version 3.6.3

**Origin**
Lepus

**Power**
Leap and bunny hop

**Notes**
Leap only moves me towards the south, regardless of how I move or where i face
Bunny hop only jumps 2 high when not sprinting or sneaking. when sprinting or sneaking its a 1 block high jump.

**Comment by EnderGirl1500** [comment]
Same issue in Fabric 0.14.14 in Minecraft 1.18.2

**Comment by QuantumXenon** [comment]
Just as a note: sneaking is supposed to prevent the extra jump (so that a player can jump by one block if they want to).

**Comment by jonask028** [comment]
@QuantumXenon in that case the origin description is (or was if its been changed) in error stating that it worked regardless of sprinting or sneaking.

**Comment by jonask028** [comment]
Looked at the patch and i see you changed it. What a Legend
