### ISSUE TITLE
Translate to Russian language

### ISSUE THREAD

**Issue by matveyvlone** [QuantumXenon/origins-plus-plus#152]
**Loader**
 Fabric

**Versions**
- Minecraft 1.19.2
- 0.14.14
- 1.7.1
- 2.0
- Pehkui 3.6.3

I have a problem with translation origins ++, i get this issue
![2023-02-20_09-51-41](https://user-images.githubusercontent.com/121692595/220035280-4c4e7b6b-0790-480d-af9b-18c72e940de5.png)
from the very beginning, I translated en_us and renamed it to ru_ru, then I threw it into the lang folder, but nothing changed when I entered the game everything was in English, then I tried to rename the file with the translation to en_us, but I got an error that I threw off above

**Comment by QuantumXenon** [comment]
Can you upload the translated version so that I can take a look?

**Comment by matveyvlone** [comment]
yes

> Can you upload the translated version so that I can take a look?
github doesn't support JSON, i try my best with txt, but it doesn't work, i can give you my discord matveyvlone#1111

**Comment by ogone4ek2090** [comment]
бро напиши мне как решили проблему дс: ogone4ekekek
