### ISSUE TITLE
Felvaxian has 2 active abilities set to G

### ISSUE THREAD

**Issue by Birbguy** [QuantumXenon/origins-plus-plus#153]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- Minecraft Version - 1.19.3
- Mod Loader Version - 0.14.14
- Origins Version - 1.8.1
- Origins++ Version - 2.0
- Pehkui Version - 3.6.3

**Origin**
Felvaxian

**Power**
Scavenger Pouch, Pounce

**Notes**
Both abilities are set to primary active power.

**Comment by QuantumXenon** [comment]
Thanks for the report!

This issue has been fixed since the latest release, so I will close this issue
