### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by APumking** [QuantumXenon/origins-plus-plus#157]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?

**Power**
What power is causing the problem?

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
Sorry, I’m not sure what your issue is. Could you please provide more details?

**Comment by QuantumXenon** [comment]
Closing due to no issue details
