### ISSUE TITLE
[Golden Golem] Flaw Not Listed on Wiki 

### ISSUE THREAD

**Issue by ItsCaptainSleepy** [QuantumXenon/origins-plus-plus#158]
Hi, So on the Wiki here on this for the Golden golem origin you seem to be missing one of the flaws that be Joint Lock Up. The flaw itself is fine just it should be listed is all. Also can you explain what the "extra little buff" is in the this: Golem Strength: You gain extra buffs depending on how much health you have. My guess is armor but i just though i would ask.

**Comment by QuantumXenon** [comment]
The (small) buffs you gain are:
- Movement Speed
- Attack Damage
- Attack Speed
- Armour
