### ISSUE TITLE
Wither Fox thief ability opens pocket

### ISSUE THREAD

**Issue by imnotliveyet** [QuantumXenon/origins-plus-plus#164]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version (Curse Forge) 0.220.2.9362
- Origins Version origins-forge-1.19.2-1.5.0.6-all
- Origins++ Version 2.0
- Pehkui Version 3.7.0

**Origin**
Wither Fox

**Power**
Thief

**Notes**
Instead of thieving, it opens a 3x3 inventory.

**Comment by QuantumXenon** [comment]
Sorry for the confusion - the withered fox cannot steal items. The power is only to open extra additional inventory space, but the description is more about adding lore and backstory to the origin.
