### ISSUE TITLE
Scale Reset on Login

### ISSUE THREAD

**Issue by DaveBxb** [QuantumXenon/origins-plus-plus#165]
Fabric

- Minecraft 1.19.2
- Origins 1.7.1
- Origins++ 2.0
- Pehkui 3.7.0
(Multiplayer)

Size resets upon rejoining server

After dying a few times I left the server, sometime later the server restarted, upon rejoining some time after that my size was the usual human size instead of the moth size

**Comment by QRQ-2817** [comment]
I'm getting this issue too with Pixie.

**Comment by QRQ-2817** [comment]
`[20:57:15] [Render thread/ERROR]: Trying to add unregistered power ResourceKey[apoli:configured_power / origins-plus-plus:pixie/bite_sized_modify_size] to entity LocalPlayer['REDACTED'/42, l='ClientLevel', x=-392.12, y=99.00, z=859.15]`
@QuantumXenon

**Comment by durrgonz** [comment]
I'm also getting this issue with the Sporeling origin, on Forge 1.19.2

**Comment by QuantumXenon** [comment]
All origins which use Pehkui seem to be sometimes have scale reset issues. I will investigate further.

**Comment by JackAttack23** [comment]
Im playing a Sever on Forage and My Size also resets, Im, tick Origin.  forage 43.2.3, Minecraft version 1.19.2
