### ISSUE TITLE
Origins lost on save restart or by configs deleted and replaced. 

### ISSUE THREAD

**Issue by SGZ-Creations** [QuantumXenon/origins-plus-plus#166]
**Loader**
Forge 43.2.7

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version: Not sure
- Origins Version 1.5.0.6
- Origins++ Version 2.0
- Pehkui Version 3.7.0

**Origin**
What origin is causing the problem? 
All of them that I've used even humane

**Power**
What power is causing the problem?
The pervious question may answer it.

**Notes**
Include any other information that might be useful here
Working on mod pack for MC 1.19.2 Forge

link to the post on other mod: https://github.com/EdwinMindcraft/origins-architectury/issues/305

**Comment by QuantumXenon** [comment]
I'm not sure why this would happen. Is it still an issue if you use v1.7.1.0 of Origins (Forge)?

**Comment by SGZ-Creations** [comment]
yes i did test that as of the update release.

**Comment by QuantumXenon** [comment]
Did you still have the same issue?

**Comment by QuantumXenon** [comment]
I don't know what I can do about it. The exact same file works as expected with Origins (Fabric), so there might be some issue with how Origins (Forge) handles it. I know there are some major bugfixes coming with the next version of Origins (Forge), so maybe try then and see if that fixes it?
