### ISSUE TITLE
Petrified hearts

### ISSUE THREAD

**Issue by kintobor115** [QuantumXenon/origins-plus-plus#168]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
 Forge

**Versions**
Minecraft Version 1.19.2
Mod Loader Version (Curse Forge) 0.220.2.9362
Origins Version origins-forge-1.19.2-1.5.0.6-all
Origins++ Version 2.0
Pehkui Version 3.7.0

**Origin**
Deathsworn

**Power**
summoning

**Notes**
I have killed around 80 skeletons with various tools and weapons no luck on petrified hearts. I did the same test of zombies and still no hearts maybe they are really rare and havent found one yet or not I really have no idea

**Comment by QuantumXenon** [comment]
This is a known issue with Forge (see #112) - for some reason, the petrified hearts don't drop from mobs. This is likely due to a bug with the Forge version of Origins as it works as expected on the Fabric version.

**Comment by KarishaDel** [comment]
Was this ever fixed?

**Comment by SBmaximill101** [comment]
will it ever be fixed??
