### ISSUE TITLE
[Warper] Random Teleport

### ISSUE THREAD

**Issue by ebug64** [QuantumXenon/origins-plus-plus#169]
**Loader**
Fabric

**Versions**
- Minecraft Version 1.19.3
- Mod Loader Version Sorry idk what this is. Mod menu? If so it's 5.1.0
- Origins Version 1.8.1
- Origins++ Version 2.0
- Pehkui Version 3.7.2

**Origin**
Warper

**Power**
Random Teleport(?)

**Notes**
The same thing happens in water but it's a bit more understandable. But as it is right now, it's impossible to explore caves cause getting shot by a skeleton or hit by anything immediately sends me back up to the surface. I assume I can change this in the Data files but I can't figure out what I'm supposed to be editing. Any help would be super appreciated!

**Comment by QuantumXenon** [comment]
At the moment, the random teleport power uses `/spreadplayers`, which teleports players on the surface. In order to fix this, I would need to find an alternative, or find a way to teleport players back underground again (neither of which I know of a method).
