### ISSUE TITLE
[Glacier] Game Crashes

### ISSUE THREAD

**Issue by Cynsai** [QuantumXenon/origins-plus-plus#170]
**Loader**
Forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version 43.2.8
- Origins Version 1.7.1.0
- Origins++ Version 2.0
- Pehkui Version 3.7.2

**Origin**
Glacier

**Power**
Not so much a specific power, but simply trying to pick the Origin at the beginning of a world, or switching to it VIA the Orb of Origin causes the game to crash.

**Notes**
I have tried on both naturally-generating worlds and superflat worlds, but neither affected the outcome. I also tried loading into both worlds in Survival mode and Creative mode, but neither changed anything. The game itself loads to the point where the Glacier's origin-specific bars pop on screen and begin to load, but then Minecraft freezes and crashes. Also important to note that this has all been in  a single player world.

On crash, the game displays the following:
"The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.getFactory()" because "power" is null"

It is important to note that I am running the Origins++ Mod alongside a bounty of other mods, so one of those could very well be the culprit. If you want a more in-depth list of everything, then I am more than happy to supply it. I specify the other mods as amongst the bunch I also have Minecraft Comes Alive which, much like Origins/Origins++ has a starting screen to press through.

**Comment by QuantumXenon** [comment]
I have been able to reproduce this crash on Forge using just Origins++ and its dependencies.

From the crash report, it looks to be a bug with Origins (Forge) (and the crash does not occur with Origins (Fabric)), so I'm not sure if there's anything I can do about it other than letting the developer know about it.

**Comment by Cynsai** [comment]
I'm relieved to hear it is not due to other mods, though certainly a troubling conclusion nevertheless. Thank you for all of your help and hard work regarding this!
