### ISSUE TITLE
Felvaxian Keybinds

### ISSUE THREAD

**Issue by BugSocks** [QuantumXenon/origins-plus-plus#171]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- Minecraft Version - 1.19.2
- Mod Loader Version - 0.14.18
- Origins Version - 1.7.1
- Origins++ Version - 2.0
- Pehkui Version - 3.7.2

**Origin**
Felvaxian

**Power**
Scavenger Pouch, Gift of the Winds

**Notes**
Both abilities are tied to the same keybind

**Comment by QuantumXenon** [comment]
Thanks for the report! This problem has been fixed since the last release, so the next version shouldn't have this issue.
