### ISSUE TITLE
Error when joining origins++ server

### ISSUE THREAD

**Issue by Pixel131** [QuantumXenon/origins-plus-plus#173]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge/Fabric

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins++ Version

**Notes**
Error displays when trying to join server

"Missing required datapack registries : moonlight:map_markers, moonlight:soft_fluids"

**Comment by QuantumXenon** [comment]
That sounds like another mod or datapack is causing the issue as Origins++ doesn't use the `moonlight:` namespace
