### ISSUE TITLE
[Shifter] Equipping Armor

### ISSUE THREAD

**Issue by Irozue** [QuantumXenon/origins-plus-plus#175]
I could not equip armor on some Origins
like the Shifter for example
thanks

**Comment by QuantumXenon** [comment]
Are you using Fabric or Forge? And what version of Origins/Origins++?

**Comment by Irozue** [comment]
almost all of it, i am mostly in feline form and i cant wear anything

**Comment by Irozue** [comment]
actually as wel while i am here, does any of these things mean anything?
![image](https://user-images.githubusercontent.com/129779911/230155271-7b5b3dd1-377c-475c-95ea-2240ddb5b562.png)

**Comment by HollowCreations** [comment]
I am also having this same issue 
I don't think its related to the missing powers error

**Comment by HollowCreations** [comment]
I am using MC 1.19.2, and the forge version of the mod

**Comment by QuantumXenon** [comment]
This is an issue with Origins (Forge) itself. I've reported it to the developers, so hopefully it is fixed soon.
