### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Rogenar** [QuantumXenon/origins-plus-plus#177]
Juggernaut
-active ability 1: hits the ground with both hands in a 7x7 area and surrounding creatures are thrown into the air and blocks are broken
-active ability 2: Throws players who are riding on it forward.
Positive advantages
+ Has 30 hearts = 60 health
+ It has natural armor because its skin is thick.
+ Can jump 2.5 blocks and walk over 1 block height.
+ Players can ride on it and throw them forward.
+ Since his lungs are wide, he can hold his breath underwater for a long time. (unlike giants can swim)
+ His arms are very strong. In this way, he can break stone and stone class blocks with his hand. Except for those containing ores.
+ Because his arms are long and strong, his melee attacks can strike from afar and deal a lot of damage. And when not holding a gun, she throws creatures backwards with her fists.
+ It cannot be pushed back as it is large and heavy.
- He has a big appetite. That's why it gets hungry so quickly.
- Moves a little slower than normal people.
- She can't hold a shield because her hand is big.
- Due to its large size and weight, it cannot ride horses, donkeys or llamas. Because mounts can't carry its weight.
- It has a height of 4 blocks and a width of 2 blocks. (It is the same size as the Giants.) So it can pass through places that are 4 blocks high and two blocks wide. (I'm putting this at a disadvantage as it will need to dig more blocks to progress while mining.)
- You have to put 4 beds together to sleep.
Note: There is a bug in the Dev class. The disadvantage of sleeping by combining 4 beds is that when we combine 4 beds, the character comes out of the bed. In Origins++ version 2.0.1

**Comment by QuantumXenon** [comment]
Thanks for the suggestion!

However, I don't plan on adding any additional origins at the moment. You could post this to `#origin-ideas` on the Origins discord server.

**Comment by Rogenar** [comment]
Can you share the link of the origin discord server?

**Comment by QuantumXenon** [comment]
https://discord.gg/origins-fabric

**Comment by Rogenar** [comment]
Thank you and even if you are not going to add this overwhelming class I would at least like to know your opinion. Can I specify this suggestion from the suggestion chat channel from the Origin mod section?
