### ISSUE TITLE
Is there a way to disable origins for 1.5.2 forge?

### ISSUE THREAD

**Issue by Korbyy** [QuantumXenon/origins-plus-plus#178]
I want the use of only a few origins but cant figure out a way on my own to disable the other origins, any way i can do this with this version of the mod? Asked earlier but i forgot to add a desc and the issue was resolved before i could comment back.

**Comment by QuantumXenon** [comment]
Sorry about that. The only version of Origins (Forge) that allows origins and powers to be disabled is v1.7.1.0 (1.19.2).

Also, is there a specific reason you are using v1.5.2? There have been a lot of improvements and fixes since then.

**Comment by Korbyy** [comment]
Sorry for the late response. I am working on making a 1.18.2 pack for me and friends to use and I have already put a fair amount of effort into making custom origins for that version. I just started learning about code and dont know much and didnt wanna risk a change of minecraft because i dont know what that would change for me when it came to the code for the custom origins ive already made. I suppose i will look into what moving versions of minecraft will do. thanks for the information QuantumXenon.

**Comment by QuantumXenon** [comment]
Custom origins _should_ work independent of the Minecraft version as there is supposed to be backwards compatibility, so I would expect any that you made for 1.18.2 to work on newer versions.
