### ISSUE TITLE
Missing Keybind

### ISSUE THREAD

**Issue by AkkiTheGamerFox** [QuantumXenon/origins-plus-plus#18]
**Origin**
Any with a ternary power

**Power**
All ternary powers

**Notes**
Simply put: There is no keybind set up for ternary powers. It cannot be bound as Minecraft does not recognize it, it's not in the controls menu and not even in the Options.txt.

**Comment by ndg-creative** [comment]
was this resolved?  Having the same issue - need to know what key the ternary abilities are bound to!

**Comment by QuantumXenon** [comment]
@ndg-creative I have the issue fixed, but I haven't released the update yet. (Hopefully it will be very soon)
