### ISSUE TITLE
Race Issue

### ISSUE THREAD

**Issue by Julexar** [QuantumXenon/origins-plus-plus#180]
**Loader**
Forge

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 43.2.1 & 43.2.8
- Origins Version: 1.5.0.6 & 1.7.1.0
- Origins++ Version: 2.0 & 2.0.1
- Pehkui Version: 3.7.2
- XL Packets Version: 2.1

**Origin**
Seemingly any Origin provided by Origins ++ (tested with Ryu and Withered Skeletian)

**Notes**
Sometimes you can't load into the World at all, instead getting the Error seen in the picture below.

Other times you can load into the World but you can't break any blocks, you don't take fall damage and no entities are moving.

![image](https://user-images.githubusercontent.com/32539080/230796920-0b56fbe6-4690-44a2-9a18-f7ef0f9ec661.png)

**Comment by Julexar** [comment]
Also here's the log if needed: [latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/11186325/latest.log)

**Comment by Julexar** [comment]
It works perfectly fine with Origins++ Version 1.7.2

**Comment by Julexar** [comment]
Okay, apparently the Mod "YungsBetterNetherFortresses" is causing the issue

**Comment by QuantumXenon** [comment]
Thanks for the report - I'm aware of this issue and have reported it as I believe that it is caused by the way that origins (Forge) handles addons.
