### ISSUE TITLE
[Withered Skeletian] Sharper Stone

### ISSUE THREAD

**Issue by RNTsubasa** [QuantumXenon/origins-plus-plus#181]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft 1.19.2
- Mod Loader Version  43.2.8
- Origins Version 1.7.1.0
- Origins++ Version  2.0.1
- Pehkui Version 3.7.2

**Origin**
Withered Skeletian

**Power**
Sharper Stone: Stone Swords do similar damage to diamond axes. (does not work, not nearly enough damage as a diamond axe)

**Comment by Julexar** [comment]
Having similar issue - stone swords don't seem to do even nearly as much damage as one would assume from the power description

**Comment by QuantumXenon** [comment]
After some investigation using target dummies, this seems to be a issue with Origins (Forge). For whatever reason, the damage isn't modified when using a stone sword. When the same power is used on Fabric, it works as expected and increases the damage. As this isn't an issue with Origins++, I will close the issue, but will pass on the information to the Origins (Forge) developers.

**Comment by QuantumXenon** [comment]
I've also added this to #112 for others to see
