### ISSUE TITLE
"Climb" stops working mid-game for all Origins

### ISSUE THREAD

**Issue by VillainousEater** [QuantumXenon/origins-plus-plus#182]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 43.2.8
- Origins Version: 1.7.1.0
- Origins++ Version: 2.0.1
- Pehkui Version: 3.7.2

**Origin**
Broodmother, Arachnid, Binturong

**Power**
Climb

**Notes**
I usually play with climbing origins but every playthrough with them, they stop working while I'm playing, completely erasing the Key Bind (it's not in the controls settings and it appears blank in the origin preview). Pressing every key and assigning toggles to every unbound key doesn't help.
This is how it looks like for every Climb ability:
![image](https://user-images.githubusercontent.com/130566165/231455849-619b060d-b3b0-49e9-a6a2-2e11f23eef77.png)

**Comment by QuantumXenon** [comment]
That's very strange. It looks like it might be an issue with Origins (Forge) though as the origins in Origins++ that use a climbing ability use the original base power.
