### ISSUE TITLE
Small origins mount

### ISSUE THREAD

**Issue by pelepa** [QuantumXenon/origins-plus-plus#183]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

when small origins mount a player or mob they float 2 blocks above the entity

**Loader**
Fabric

**Versions**
- 1.19.3
- 0.14.19
- 1.8.1
- 2.0.1
- 3.7.2

**Origin**
All origins that shrink the player

**Power**
Mount

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
Thanks for the report! I don't think there is anything I can do about that though as it seems to be unintended behaviour between Pehkui and Origins itself.
