### ISSUE TITLE
[Shifter] Origin Switching

### ISSUE THREAD

**Issue by SticcManAlt** [QuantumXenon/origins-plus-plus#184]
Hello, I have been selected with the shifter class, but none of the abilities work, even with the correct special item.

Fabric

**Versions**
Minecraft Version, 1.18.2
Mod Loader Version, .14.14
Origins Version, 1.18.2-1.4.1
Origins++ Version, 2.0
Pehkui Version, 3.7.01.14.4-1.19.3

**Origin**
Shifter

**Power**
All powers connected to switching origins, not the passive abilities, however (from what I can tell with the Avian)

**Notes**
I have already tested this with origins plus plus 2.0.1, and still no.

**Comment by QuantumXenon** [comment]
Closing due to no updates

**Comment by SammyLeeee** [comment]
what is the special item?

**Comment by SammyLeeee** [comment]
i cant use the switch power of the shifter
