### ISSUE TITLE
[Illusioner] + [Voidling] Missing Wiki Pages

### ISSUE THREAD

**Issue by bunger1** [QuantumXenon/origins-plus-plus#186]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?

**Power**
What power is causing the problem?

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
I'm in the process of finding a good page design for those as they both have three tiers

**Comment by QuantumXenon** [comment]
Pages completed
