### ISSUE TITLE
Client Time Out, Still on Server

### ISSUE THREAD

**Issue by Sad-yst** [QuantumXenon/origins-plus-plus#187]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge 

**Versions**
- Minecraft Version 1.18.2
- Mod Loader Version 4.2.2
- Origins Version 1.5.0.1fatjar
- Origins++ Version 2.0
- Pehkui Version 3.7.3

**Origin**
What origin is causing the problem?

i believe all of them, it times every single player's client out of the game upon someone's death or attempt to choose an origin upon joining, that being said,the server shows that the player characters are still in the game bit clients aren't connected and when attempting to get on, it says timed out this happens with any origin except for human, restarting the server helps and we are using aternos, 
some origins end up instantly disconnecting the player and unless reset to human the player can't get in game whatsoever

**Power**
What power is causing the problem?

the only issues with powers we have is that they skills are all bound to one hotkey and lava vision isn't working

**Notes**
Include any other information that might be useful here

as i started in origins, the issue is the  ridiculous timing out while supposedly being in the game, on the server still?I'm genuinely confused
the only way to choose an origin is to use the orb after taking human and hope it's not the one that instakicks out of game with "internal server error" , or pray to stay alive because dying and respawning causes the same timed out issue

**Comment by QuantumXenon** [comment]
I don't know why this would be happening. Does it still occur if you use other versions of Origins (Forge)?
The shared keybinds issue is a bug with Origins (Forge) itself on 1.18.2.

**Comment by Sad-yst** [comment]
i didn't test that out, the issue seems to be connected to apoli, when i reinstalled it, it started working
i don't know if choosing origin upon logging for the first time works, but dying does

**Comment by Sad-yst** [comment]
> I don't know why this would be happening. Does it still occur if you use other versions of Origins (Forge)? The shared keybinds issue is a bug with Origins (Forge) itself on 1.18.2.

sadly the timing out issue is still happening, we launched a new world and no matter how many times i tried to reinstall it,upon dying or attempting to choose an origin the exact same thing happened. i will try testing 1.19.2 out to see if it still occurs and let you know,for now,sadly,i was forced to remove your mod which really sucks given the fact that ive gotten used playing as wither fox. i genuinely dont know what to do atp

**Comment by QuantumXenon** [comment]
Did trying 1.19.2 help?

**Comment by QuantumXenon** [comment]
Closing due to no updates
