### ISSUE TITLE
Add support for origins:ignore_diet

### ISSUE THREAD

**Issue by muon-rw** [QuantumXenon/origins-plus-plus#189]
**Origin**
All Origins with custom diet powers 

**Balance Suggestion**
Add an inverted `tag: origins:ignore_diet` item condition to an origins:or under all of your food-based restrict_item_usage powers.

**Why:**
The Ignore_diet tag is used for, for example, whitelisting foods that gate gameplay progression, such as meef stroganoff from twilight forest. 

The base origins:carnivore and origins:vegetarian powers have this implemented.

**Comment by QuantumXenon** [comment]
Thanks for the suggestion! I'll add this, though I am quite busy at the moment
