### ISSUE TITLE
Size resetting on login

### ISSUE THREAD

**Issue by durrgonz** [QuantumXenon/origins-plus-plus#190]
**Loader**
Forge

**Versions**
- Minecraft 1.19.2
- Forge Version 43.2.0
- Origins Version 1.7.1.0
- Origins++ Version 2.0.1
- Pehkui Version 3.7.3

**Origin**
Any origin that changes the player's size

**Power**
All size-changing powers

**Notes**
I am hosting a modded Forge server using Pebblehost, however, the problem also persists in singleplayer. If a player logs out and logs back into the server, their size will be reset to default, as well as any other attributes changed by Pehkui. I've tried manually changing players' sizes using the scale command, but the problem still remains upon them relogging. I'm unsure what could be causing this, any help would be greatly appreciated!

**Comment by QuantumXenon** [comment]
Merging with #165
