### ISSUE TITLE
Add a config option for balancing?

### ISSUE THREAD

**Issue by akanthasAurae** [QuantumXenon/origins-plus-plus#191]
**Origin**
Which origin needs the balance?
The Deranged origin
**Power(s)**
Which power(s) need(s) to be balanced?
The derangement bar
**Balance Suggestion**
Do you have any ideas about how it could be balanced?
Sorry for the edit, hit shift-enter on habit. But I believe a form of editing the values of how the derangement bar is filled could be a good way to balance the origin per-server or user (if singleplayer). Maybe just the value of how much one kill fills the bar or the total value of the bar itself.

**Comment by QuantumXenon** [comment]
I made a small change to the number of hits needed, but I don't think I will add a way to adjust this as it would be quite complicated to implement and I don't have any plans to do that at the moment. Thanks for the suggestion though!
