### ISSUE TITLE
Removing Effects

### ISSUE THREAD

**Issue by BinnyBoi27** [QuantumXenon/origins-plus-plus#192]
**Origin**
Which origin needs the balance?
Fallen Angel
**Powers**
None of the powers are an issue. 
**Balance Suggestion**
I would like to know how to remove the translucent and glowing effects from Fallen Angel

**Comment by QuantumXenon** [comment]
If you go into the origins config file, you can turn of the specific powers `origins-plus-plus:fallen-angel/glowing` and `origins-plus-plus:fallen-angel/translucent` to remove those two effects
