### ISSUE TITLE
Ryu and Wither Skeleton origin removing users from teams - Fabric

### ISSUE THREAD

**Issue by Mossy-Skies** [QuantumXenon/origins-plus-plus#193]
**Loader**
Fabric

**Versions**
Minecraft - 1.19.2
Fabric Launcher 0.14.19
Origins Version - 1.7.1
Origins++ Version - 1.7.2
Pehkui Version - 3.7.2

**Origin**
Ryu and Wither Skeleton

**Power**
Not a specific power, but seeming the origin themselves

**Notes**
Two of my players on a server are unable to use the 'Vanilla Tweaks Color Name' datapack, and after some testing and troubleshooting with help from the Vanilla tweaks server, I've found out that these two origins seem to remove players from teams, as no one else is having an issue.

**Comment by QuantumXenon** [comment]
I think I know why this might be happening (these origins add teams to get certain mobs to be passive to them), but I'm not sure how I would fix the issue you are describing without breaking the current functionality.

**Comment by QuantumXenon** [comment]
As you cannot be a part of multiple teams at the same time (as far as I am aware), any origin which uses teams will not be compatible with the color names data pack you are using. 

Unfortunately, the teams are needed for core mechanics of the origins (such as passive nether mobs for the withered skeletian), as such Origins++ will be incompatible with that and similar datapacks as I would like to keep the functionality of these origins.
