### ISSUE TITLE
Webshot Ability Unusable

### ISSUE THREAD

**Issue by Murasaki2142** [QuantumXenon/origins-plus-plus#194]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?
Fabric
**Versions**
- Minecraft Version: 1.19.3
- Mod Loader Version: Latest
- Origins Version: "Origins-1.19.3-1.8.1"
- Origins++ Version: "origins-plus-plus-2.0.1"
- Pehkui Version: "Pehkui-3.7.3+1.14.4-1.20"

**Origin**
What origin is causing the problem?
Broodmother
**Power**
What power is causing the problem?
Web Shot
**Notes**
Include any other information that might be useful here
I'm unable to use the webshot ability at all, i changed the keybind multiple times restarted my game multiple times, and had the server restarted

**Comment by QuantumXenon** [comment]
Were you wearing boots and on the ground? I see that I missed out the part in the description where it says you cannot be wearing boots and must be on the ground for it to work

**Comment by QuantumXenon** [comment]
[6c4ee50](https://github.com/QuantumXenon/origins-plus-plus/commit/6c4ee507e1899979ec9a4afa08a4ac5d8d10bdb0) adds the missing description part
