### ISSUE TITLE
Technomancer charge not working

### ISSUE THREAD

**Issue by azmoose007** [QuantumXenon/origins-plus-plus#195]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?

**Power**
What power is causing the problem?

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
What about it isn't working? Can you not charge the mana, or can you not use it?

**Comment by QuantumXenon** [comment]
Closing due to lack of information
