### ISSUE TITLE
[Triangulon] - Walking on liquids has problems when in liquid

### ISSUE THREAD

**Issue by Sehva** [QuantumXenon/origins-plus-plus#196]
**Loader**
Fabric

**Versions**
- Minecraft Version - 1.19.2
- Mod Loader Version - 0.14.19
- Origins Version - 1.7.1
- Origins++ Version - 2.0.1
- Pehkui Version - 3.7.3+1.14.4-1.20

**Origin**
Triangulon

**Power**
Gravity Manipulator, Lava Walk

**Notes**
When walking on either Water or Lava, it is normally not possible to sink. You can sink to the bottom if the liquid is flowing or if there is another block inside the water block (such as Kelp). When that happens you cannot jump or enter creative flight, so it becomes very difficult to escape.
I'm not sure if this is intended, but the descriptions make it seem, that you should be able to go into liquids too, and the behavior when you're in a liquid seems very bugged.

**Comment by QuantumXenon** [comment]
I've also had this issue when playing with origins that use `origins:walk_on_fluid`, so it might be an issue with how that works on Origins, but I can have a look to see if I can find a solution.

**Comment by QuantumXenon** [comment]
Try updating Origins to a newer version (such as `1.9.0`). I've done some testing and the issues seem to be fixed.
