### ISSUE TITLE
custom textures?

### ISSUE THREAD

**Issue by abrokenmirror** [QuantumXenon/origins-plus-plus#197]
was wondering if there was a way i could customize the texture of my moth wings? or is there's a way to customize any origin's elytra. since the elytra is already equipped, we can't name it in an anvil or anything. is there a way to get around this? thanks !

**Comment by QuantumXenon** [comment]
The moth uses the default elytra texture, so if you made/found a resource pack to retexture the standard elytra, it should also apply to the moth wings. Let me know if that doesn't work.

**Comment by abrokenmirror** [comment]
got it, ok second question lol, is there a way we could make to where each origin (with an elytra) has their own wing textures. since if we used a resource pack with a texture that would change everyones to one texture. i'm on an smp with other people that would also like to have their own custom elytras and its absolutely sucking the life out of me trying to figure out how we could get it to work LMAO. thanks again !

**Comment by QuantumXenon** [comment]
I am not aware of a way to have custom textures for different players without using `CustomModelData`, which I don't know how I would be able to implement in a way for each player to have a different tag.

 `CustomModelData` is currently used with other origins, like the Technomancer, but the items do not have personalised textures per player, only retexturing specific items.
