### ISSUE TITLE
I am unable to equip any armor as a shifter 

### ISSUE THREAD

**Issue by HollowCreations** [QuantumXenon/origins-plus-plus#199]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?

**Versions**
- Minecraft Version - 1.19.2
- Mod Loader Version
- Origins Version 1.19.2-1.7.1.0
- Origins++ Version 2.0O
- Pehkui Version 3.73+1.19.2-forge

**Origin**
What origin is causing the problem? Shifter

**Power**
What power is causing the problem? None, but I am completely unable to equip any armor to my player character 

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
Thanks for the report! I'm going to close this as it is related to #175 (I see that you've also seen that issue), so that everything related to this is in one place
