### ISSUE TITLE
[Giant] Unable to mount even though config is set to false.

### ISSUE THREAD

**Issue by gorbodoh** [QuantumXenon/origins-plus-plus#200]
I have tried setting the mount config to true and false on both server side and client side, however when mounting the mount still kick the user out.

**Comment by QuantumXenon** [comment]
Are you using Fabric or Forge?

**Comment by gorbodoh** [comment]
Hi, I am using Fabric. However, this might not be a bug at all - after repeated testing and feedback from players, I realized this config is for fetching mobs and for players to hike on.

I thought this was a setting for if Giants could mount on horses, boats and minecarts - I would like to request for one, but should I open a new thread? You may close this thread for now. Thanks!

**Comment by QuantumXenon** [comment]
So this is not currently possible to disable in v2.0.1 without also disabling some other powers. It is currently located under `origins-plus-plus:giant/swim`, but I will split this into a separate power for the next update.

**Comment by QuantumXenon** [comment]
In the next update, this power can be found at `origins-plus-plus:giant/prevent_mount` which can be disabled in the config.
