### ISSUE TITLE
connectivity seems to not be detected

### ISSUE THREAD

**Issue by 1248013** [QuantumXenon/origins-plus-plus#202]
So im trying to make a custom modpack and see that you need connectivity 3.3 or higher in order to use origins plus plus but no matter what version i download whether it be 4.2 all the way down to 3.3 it constantly says its not working 
![image](https://github.com/QuantumXenon/origins-plus-plus/assets/93271836/3027754c-3ecd-4e3b-a55f-d97b9d85933f)

**Comment by QuantumXenon** [comment]
From what I can tell, you are using the Fabric file on Forge. There was a mistake in the `mods.toml` file for that version, so I would suggest trying the Forge file (https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus/files/4476127) which I have checked and has the correct version range.

I have split the files to improve my ability to troubleshoot and manage dependencies, so sorry if there was any confusion.
