### ISSUE TITLE
Derangement Bar not filling

### ISSUE THREAD

**Issue by Doconus** [QuantumXenon/origins-plus-plus#204]
**Loader**
Forge

**Versions**
- Minecraft Version (1.18.2)
- Mod Loader Version (40.2.1)
- Origins Version (1.4.1.4)
- Origins++ Version (2.0)
- Pehkui Version (3.7.2)

**Origin**
Deranged

**Power**
Derangement bar

**Notes**
-Derangement bar not filling
-Added origins++ to medieval Minecraft 1.18.2

**Comment by QuantumXenon** [comment]
I think this is an issue with Origins (Forge) because it works as intended with the Fabric version.
