### ISSUE TITLE
rat origin scale bug

### ISSUE THREAD

**Issue by squeakybatboi** [QuantumXenon/origins-plus-plus#208]
**Loader**
Forge

**Versions**
- Minecraft Version 1.18.2
- Mod Loader Version 40.2.9
- Origins Version 1.18.2-1.4.1.4-unified
- Origins++ Version 2.0-forge
- Pehkui Version 3.7.5+1.18.2-forge

**Origin**
rat

**Power**
one block height

**Notes**
whenever i exit a world (both singleplayer and multiplayer), and then re-enter the same world, my size is reset to normal two-block height. my only solution is to enter /origins set @s origins:origin origins-plus-plus:rat to force my height back down to half a block. this is an okay fix for now, but it's still rather bothersome to have to do every time i enter a world where my origin is rat.

and no i will not switch to the mouse origin. i believe in rat supremacy.

**Comment by QuantumXenon** [comment]
Merging with #165
