### ISSUE TITLE
Anomaly flashing and issues with giant 

### ISSUE THREAD

**Issue by SleepingMars** [QuantumXenon/origins-plus-plus#209]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Origins++ Version

**Origin**
What origin is causing the problem? anomaly, giant, and bedrockean

**Power**
What power is causing the problem?
giant keeps sending animals into the void. bedrockean and anomaly screens keep flashing.

**Notes**
Include any other information that might be useful here
on a server. don’t know if that effects anything

**Comment by QuantumXenon** [comment]
I tested the three issues that you mentioned on the Fabric version and was not able to replicate them, so I believe these are issues with Origins (Forge) itself.
