### ISSUE TITLE
Land Sharks cannot eat some other mods meat included food

### ISSUE THREAD

**Issue by SaxDev** [QuantumXenon/origins-plus-plus#211]
**Origin**
Which origin needs the balance?
Land Shark

**Power(s)**
Which power(s) need(s) to be balanced?
Carnivore

**Balance Suggestion**
Do you have any ideas about how it could be balanced?
I'd like it so it is actually compatible with mods such as Farmer's Delight, Cooking for Blockheads or Aquaculture 2 which contain meat meals, i couldnt find a config file where i could add my own food either. Id like if the foods we can eat was in a seperate file or config so we can modify it for our modpacks.
![image](https://github.com/QuantumXenon/origins-plus-plus/assets/30241194/f0f5a3f7-1fb2-428e-9ed8-f824ffbcd70d)
![image](https://github.com/QuantumXenon/origins-plus-plus/assets/30241194/2450db91-a62a-4399-8ed9-961b753f86c1)

**Comment by QuantumXenon** [comment]
Thanks for the suggestion! I'm already planning on introducing two ways to avoid this problem -
1) Use `origins:ignore_diet` to allow datapacks to add items to be eaten by any player
2) Add some form of mod compatibility to allow items to be added to any of the tags used by Origins++

These (hopefully) should be coming in the next few weeks to prevent issues like these from occurring in the future.
