### ISSUE TITLE
java.util.concurrentmodificationexception on world load.

### ISSUE THREAD

**Issue by ThreeForths** [QuantumXenon/origins-plus-plus#212]
*Please check the pinned issues "Known Forge Issues" and "v2.0 Known Issues" before posting a new report*

**Loader**
Forge

**Versions**
- 1.18.2
- Mod Loader Version
40.2.9
- Origins Version
1.4.1.4
- Origins++ Version
v2.0
- Pehkui Version
3.7.5
**Origin**
What origin is causing the problem? 
N/A

**Power**
What power is causing the problem?
N/A

**Notes**
With this mod installed, on world load I get this error. java.util.concurrentmodificationexception
Logs dictate a bad packet was sent? Unsure what would be calling this error.

**Comment by QuantumXenon** [comment]
Could you attach a log?

**Comment by ThreeForths** [comment]
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/11780407/latest.log)

**Comment by ThreeForths** [comment]
Here is the latest log. When I remove Origins++ the problems all go away.

**Comment by QuantumXenon** [comment]
This might be a bug with how Origins (Forge) handles addons. A lot of major bugs were fixed in 1.19.2 so this might have been one of them
