### ISSUE TITLE
Missing Origin Descriptions

### ISSUE THREAD

**Issue by TheRednax** [QuantumXenon/origins-plus-plus#213]
**Loader**
Forge 

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version 43.2.14
- Origins Version 1.7.1.0
- Origins++ Version 2.0.1
- Pehkui Version 3.7.5

**Origin**
all

**Power**
Explanation

**Notes**
So, me and my friends have a server. We use this mod it's a lovely one by the way. But every time I use the orb I can see the advantages of each origin and disadvantages, explanations about them, powers, etc. However, I am the only one of us who can see them. All the other people can't see the advantages, etc ingame, and have to check the wiki.
I don't know if this is a faulty thing on my end, the server's end, or my friend's end. 
(btw) they are all using a copy of my mod files.

**Comment by QuantumXenon** [comment]
I've seen this reported a few times before, but I don't know the cause. It only happens with the Forge version, which leads me to believe that it's caused by Origins (Forge) having issues dealing with the large number of origins and descriptions.
