### ISSUE TITLE
Damage teleport bug with malfuncion.

### ISSUE THREAD

**Issue by NotABot2009** [QuantumXenon/origins-plus-plus#214]
*Please check the pinned issues "Known Forge Issues" and "v2.0 Known Issues" before posting a new report*

**Loader**
Forge or Fabric?

Fabric

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

origins ++ version

**Origin**
What origin is causing the problem?

Malfunction

**Power**
What power is causing the problem?

the teleportation on damage

**Notes**
Include any other information that might be useful here

every time you take damage you get teleported to the highest point. In caves you get teleported to the surface. I'm not sure if this is intentional but it makes it very hard to play

**Comment by QuantumXenon** [comment]
This is due to the power using `/spreadplayers`, so unless I find an alternative implementation, this will not be able to be fixed.

Note: I have an idea to partially fix this
