### ISSUE TITLE
[Warper] Teleport

### ISSUE THREAD

**Issue by ApathyTV** [QuantumXenon/origins-plus-plus#217]
*Please check the pinned issue "Known Forge Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- 1.18.2

**Origin**
Warper

**Power**
When my friend uses his Warper skill I get teleported to him no matter what I do. I tried rejoining and changing my origin but I keep getting teleported to him 

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
Which warper skill are do you mean? Could you provide the name?

**Comment by QuantumXenon** [comment]
I'm not sure why this would be happening, but I made a change that might fix the issue. Please reopen this issue if you still have the problem after updating to v2.1 (which will release later today).
