### ISSUE TITLE
[Mouse] Main Ability

### ISSUE THREAD

**Issue by Cats1595** [QuantumXenon/origins-plus-plus#218]
*Please check the pinned issue "Known Forge Issues" before posting a new report*

**Loader**
Fabric

**Versions**
Minecraft 1.19.3
Fabric 0.14.21
Origins 1.8.1
Origins++ 2.0.1
Pehkui 3.7.6

**Origin**
Mouse

**Power**
Main ability

**Notes**
It teleports other players to me on the server I'm on

**Comment by Cats1595** [comment]
I should clarify it only teleports a specific player to me

**Comment by QuantumXenon** [comment]
I'm not sure why this would be happening, but I made a change that might fix the issue. Please reopen this issue if you still have the problem after updating to v2.1 (which will release later today).
