### ISSUE TITLE
Origins with altered sizes revert on death/relog

### ISSUE THREAD

**Issue by Bledynn** [QuantumXenon/origins-plus-plus#219]
*Please check the pinned issue "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 43.2.6
- Origins Version: 1.7.1.0
- Origins++ Version: 2.0.1
- Pehkui Version: 3.7.6

**Origin**
Any Origin that changes player size (specifically tested with Gaia, Flea, Mouse).

**Power**
None applicable

**Notes**
Player size resets on death or when reconnecting to server. Attempted fresh installation of mod files via Curseforge, same result.

**Comment by QuantumXenon** [comment]
Thanks for the reply! This should be fixed in the next version which should come out tomorrow. If the issue persists with the new version, please reopen the issue.
