### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by FiftiethTerror5** [QuantumXenon/origins-plus-plus#220]
*Please check the pinned issue "Known Forge Issues" before posting a new report*

**Loader**
Forge or Fabric?

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?

**Power**
What power is causing the problem?

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
Closing empty issue
