### ISSUE TITLE
(From #219) Origins with altered sizes revert on death/relog 

### ISSUE THREAD

**Issue by Bledynn** [QuantumXenon/origins-plus-plus#222]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 43.2.6
- Origins Version: 1.7.1.0
- Origins++ Version: 2.0.1
- Pehkui Version: 3.7.6

**Origin**
Any Origin that changes player size (specifically tested with Gaia, Flea, Mouse).

**Power**
None applicable

**Notes**
Player size resets on death or when reconnecting to server. This is on the newest version of Origins++ that was released today.

**Comment by QuantumXenon** [comment]
I don’t know what to do about this. I have a possible solution, but it isn’t ideal. I won’t get a chance to try it until next week though.

**Comment by QuantumXenon** [comment]
I’ve used the new method, again, reopen the issue again if that doesn’t work
