### ISSUE TITLE
 Origin can't eat special foods.

### ISSUE THREAD

**Issue by Fooddude99** [QuantumXenon/origins-plus-plus#223]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge or Fabric? 
Fabric

**Versions** 
- Minecraft Version: 1.19.4
- Mod Loader Version: 0.14.20
- Origins Version: Origins-1.19.4-1.9.0
- Origins++ Version: origins-plus-plus-2.1
- Pehkui Version: Pehkui-3.7.5+1.14.4-1.20

**Origin**
What origin is causing the problem?
Warper (Could be other Origins but I haven't tested it)
**Power**
What power is causing the problem?
Cannot eat endstone. 
**Notes**
Include any other information that might be useful here

This is on a server I run. I updated the mod to find my origin could no longer eat Endstone. I reset the config, disabled and reenabled the power, and still nothing. I even added the data pack and still nothing. I don't know if the update affected any other origin that eats special blocks/items but I'm guessing it involves the powers involving eating with right-clicking or it could be just Warper.

**Comment by QuantumXenon** [comment]
Hmm, I have an idea of what might be the problem (the tag is under ‘blocks’ instead of ‘items’), but I will not get a chance to fix it until next week.

**Comment by Fooddude99** [comment]
Thats ok. Luckily I'm the only warper on the server. And the teleport bug was fixed from this update so I'm in no rush. Ty for responding.
