### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rogenar** [QuantumXenon/origins-plus-plus#224]
When I add Origin++ mod, I can't choose origin or sometimes I get a connection lost error when creating world. I had encountered this problem in previous versions and it was solved by downloading a mod. But I forgot the name of that mod.

**Comment by terrarian10** [comment]
Do you have any other mods whatsoever, you need origins for this to work. Otherwise IDK

**Comment by Rogenar** [comment]
yes there are other mods and there is origin mod

**Comment by QuantumXenon** [comment]
Can you attach a log?

**Comment by Rogenar** [comment]
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/11981606/latest.log)
[rei.log](https://github.com/QuantumXenon/origins-plus-plus/files/11981609/rei.log)
[rei-issues.log](https://github.com/QuantumXenon/origins-plus-plus/files/11981618/rei-issues.log)
When I add the origin plus mod, it causes me to enter without choosing an origin when creating the world.

**Comment by QuantumXenon** [comment]
Try installing [XL Packets Fabric](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) and/or [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity)

**Comment by Rogenar** [comment]
problem fixed.
