### ISSUE TITLE
Dying as a Warper disables respawn button.

### ISSUE THREAD

**Issue by DooveyTheDoove** [QuantumXenon/origins-plus-plus#225]
**Loader**
Fabric

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version
- Origins Version: 1.7.1
- Origins++ Version: 2.1
- Pehkui Version: 3.7.6

**Origin**
Warper (and other origins that spawn in the end)

**Problem**
Dying in the end disables respawn, like i can't press the respawn button, only the title screen button works. I apologize if this is the wrong place to report this issue but i just felt like the Origins++ mod is causing this. 

Update: Dying from anything as a warper prevents you from respawning.

**Comment by QuantumXenon** [comment]
This is caused by issues with respawning in unloaded areas which causes the game to hang
