### ISSUE TITLE
Deathsworn SOULs

### ISSUE THREAD

**Issue by SzalaiRicsi** [QuantumXenon/origins-plus-plus#227]
**Loader**
Forge 

**Versions**
- 1.19.2

**Origin**
Deathsworn

**Issue**
Petrified souls don't drop.

I don't get any petrified souls. Seen it in the known bug but not sure if it is fixed or not because that one wasn't updated recently I think. Is it fixed?

**Comment by QuantumXenon** [comment]
No, this is an issue with Origins (Forge) but should be fixed when they release the next update
