### ISSUE TITLE
forge light mage

### ISSUE THREAD

**Issue by firekings324** [QuantumXenon/origins-plus-plus#230]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge 

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version 43.2.14
- Origins Version 1.19.2-1.7.10-all.jar
- Origins++ Version 2.1
- Pehkui Version 3.7.6

**Origin**
light mage

**Power**
special power pocket dimension leave

**Notes**
i can use the pocket dimension enter and create fine but i cant leave when i do i tp to the roof of the nether then back to the pocket dimension.

**Comment by QuantumXenon** [comment]
I tested this in a world with just Origins++ (and latest versions of dependencies) and I did not experience any issues, perhaps it was fixed in an update since your issue occurred?
