### ISSUE TITLE
Origin Update 

### ISSUE THREAD

**Issue by ghost** [QuantumXenon/origins-plus-plus#231]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

Loader
Forge or Fabric?
Fabric

Versions

Minecraft Version: 1.19.4
Mod Loader Version: 0.14.20
Origins Version: Origins-1.19.4-1.9.0
Origins++ Version: origins-plus-plus-2.1.1
Pehkui Version: Pehkui-3.7.5+1.14.4-1.20

**Origin**
What origin is causing the problem?
1. The mod itself. Updated the mod and all players with origins from the mod when entering the server had no oriign and none of the origins from the mod are listed as an option. 

2. I personally am receiving the message "Invalid Player Data"
**Power**
What power is causing the problem?
N/A
**Notes**
Include any other information that might be useful here
Here is what the server is saying when I join:
Origin with id origins-plus-plus:warper is not in layer origins:origin and is not special, but was found on empty, setting to EMPTY.

**Comment by Fooddude99** [comment]
Before anything else happens I did update another origin mod. I downgraded them both and currently testing which one is causing the problem

**Comment by QuantumXenon** [comment]
Could you please check the most up to date version is also on the server?
