### ISSUE TITLE
Origin overworld spawn

### ISSUE THREAD

**Issue by Kulei666** [QuantumXenon/origins-plus-plus#232]
**Loader**
Fabric

**Versions**
- Minecraft Version 1.19.4
- Mod Loader Version 0.14.21
- Origins Version 1.9.0
- Origins++ Version 1.6.0
- Pehkui Version 3.7.6

**Origin**
Any Origin that spawns you in the overworld in a different place mineshaft/ocean. Tested with Dolphin and Broodmother. Spawning in Nether works, tested with Blazeborn.

**Notes**
If it finds ocean or a mineshaft it manages to teleport there, but otherwise it crashes the server. (or the internal server on singleplayer)

**Comment by QuantumXenon** [comment]
I believe this is caused by the server hanging when trying to find a location to spawn. This is most likely an issue with the way Origins itself finds spawn locations, so there isn’t really anything I can do without removing these powers
