### ISSUE TITLE
Giant Origin

### ISSUE THREAD

**Issue by KoalaKat303** [QuantumXenon/origins-plus-plus#233]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Origins++ Version

**Origin**
The Giant origin

**Power**
The size won't apply when I log into the world and I have to reset my character through death. Also I cannot wear any armour aside from a chestplate. This was fine and livable until your recent update where now even when I reset my character, I still stay 2 blocks tall instead of 4. At this point, there's no point in being a Giant when I can no longer be giant at all.

**Notes**
The Giant is my preferred origin and I've had a lot of fun building to accommodate my size, even though the origin has been broken the entire time I've played it, I've found a way to work with it. But now I can't even do that.

**Comment by KoalaKat303** [comment]
I'll be honest I didn't understand what you meant by versions but my friends and I are playing on 1.19.2

**Comment by QuantumXenon** [comment]
The armour portion is an issue with Origins (Forge) that should be fixed in the next version. As for the size issues, I will have a look at them soon

**Comment by QuantumXenon** [comment]
I have tested this with the new version, and it seems to be working correctly now. If you still have issues, please reopen this issue.
