### ISSUE TITLE
Felvaxian is a bit much

### ISSUE THREAD

**Issue by Datbanana** [QuantumXenon/origins-plus-plus#237]
**Origin**
Felvaxian

**Power(s)**
General origin overall just seems to have too much going on/very powerful

**Balance Suggestion Preface**
I dont know how the workflow works for balancing, but if it were up to me a lot of the powers should just outright be removed, ill make two different suggestions of more and less conservative of the base origin just in case thats not really a thing though
 
(general idea on these is this seems to be a mix of elytrian, shulk, and feline, so i felt best solution was to have it be a "jack of all trades, master of none" sort of situation)

**More Aggressive Balancing Suggestion**
Outright remove pounce or feline's legs, they both do the same thing and only clutter
Remove gift of the winds but keep ability to use elytra, if possible give a small hunger drain while flying
Change amount of hearts to 8 instead of 9
Change unholy aura to make you unable to trade with villagers, ravens are an ill omen and this will help with the lax downsides
Remove tigers roar, or nerf it hard as the speed boost you gain from it is ridiculous. this origin has too much abilities anyway
Change scavengers pouch to only be able to hold an item or two, i dont know if it keeps those items on death because i cant bind 3 ability keys but it it doesnt free free to let it do that

**Less Aggressive Balancing Suggestion**
Still remove pounce or feline's legs, it really does clutter the origin
Keep gift of the wind but nerf it to a full minute cooldown, the hunger drain still seems a good idea if possible
Making unholy aura be a downside is still a good plan, no villagers is a big blow to counteract how much this origin has
Please just remove tigers roar, it recharges so fast its functionally infinite and the origin already has a speed boost from felines legs
no chaage needed for scavengors pouch, though  it may be a good idea to add a downside or two for having it be there, maybe no armor better than iron? could do it be unable to mine natural stone like the feline instead (perhaps less strict though, was never a fan of that downside

**Comment by QuantumXenon** [comment]
Thanks for the suggestion! I will make some changes to the origin for the next update using your feedback

**Comment by QuantumXenon** [comment]
I've made several changes according to your feedback. These will be included in the next version for you to test out.
