### ISSUE TITLE
Deranged - Derangement Bar Won’t Fill

### ISSUE THREAD

**Issue by ScrumboPapkins** [QuantumXenon/origins-plus-plus#238]
**Loader**
Fabric

**Versions**
- Minecraft Version 1.18.12
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?
Deranged

**Power**
What power is causing the problem?
Insanity / Derangement Bar

**Notes**
Whenever I kill anything (friendly mob, hostile mob, another player) the Derangement bar does not increase by 25, it stays at 0. Is this a bug or am i not killing the right thing.

**Comment by QuantumXenon** [comment]
I was unable to replicate this issue using 1.18.2 Fabric with the latest versions of all dependencies. Perhaps check everything is up-to-date and see if you still have the issue, if not, please reopen this issue and include logs.
