### ISSUE TITLE
"You can not have any Origins."

### ISSUE THREAD

**Issue by Tenktv** [QuantumXenon/origins-plus-plus#239]
**Loader**
Fabric?

**Versions**
- Minecraft Version: Fabric  0.14.21
- Origins Version : 1.19.2-1.7.1
- Origins++ Version: 1.7.1
- Pehkui Version : Pehkui-3.7.7+1.14.4-1.20.1.jar

**Origin**
The Mod

**Power**
IDK

**Notes**
When I want to run this mod on fabric it dont work. I cant pick any origins and if I try with Orb of Origins it just disappear. I know that this mod is the problem bc when I remove it everything works fine. I hope anyone knows the problem and can help me.

**Comment by QuantumXenon** [comment]
I was unable to replicate this issue using the setup you had with the latest versions of everything for 1.19.2. Please reopen the issue if you are still experiencing the issue and include logs.
