### ISSUE TITLE
[Withered Fox] [Float]

### ISSUE THREAD

**Issue by Niko8389** [QuantumXenon/origins-plus-plus#24]
**Origin++**

The “withered fox” origin

**Power**
“Float ability”
The float ability never stop’s, even when you are exhausted, you still keep going up. There’s  no limit for your use of this ability.

you can’t jump normally I’m not sure if it was intended  that way. You can’t jump without floating upwards.
**Notes**

**Comment by QuantumXenon** [comment]
Replacing jumping with floating is intended, but I am working on a fix to the infinite flight.
