### ISSUE TITLE
Marshmallow origin idea

### ISSUE THREAD

**Issue by Foxxxy26** [QuantumXenon/origins-plus-plus#240]
I'm not sure who to go to for this but I was thinking since I've been playing Marshmallow I've seen some flaws in it.. in my opinion at least

Marshmallows are sugar and air, so why does it sink like a rock?
 - It should float on water, but "dissolve" taking damage over time from the water
 
 Being crispy making you stronger?
  - I think it'd be better to get rid of that and switch that bar out for a "sugar" bar, where the more sugary things you eat the bigger you get (once you hit certain milestones). But the bigger you get the slower you are and maybe you do a bit more damage? Maybe you could sink in water at max size?
  - When your sugar bar is empty your tiny, you move faster, you have less hp and you do less damage.
  
  How does the sugar bar empty?
   - could be set to go away over time or it gets melted away by hot things/biomes, could also be "washed" away by water and rain.
   - You can only fill it if you drink honey bottles or better yet eat whole honey blocks, maybe a honey block only filling 1/10th of the bar? Maybe less so it's not too easy to get big?

**Comment by QuantumXenon** [comment]
Thanks for the suggestion! I will make some changes to the origin for the next update using your feedback

**Comment by QuantumXenon** [comment]
I've made these changes, so they will be included in the next update
