### ISSUE TITLE
Bedrockean Bedrock break not working

### ISSUE THREAD

**Issue by Sensa16** [QuantumXenon/origins-plus-plus#241]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Origins++ Version

**Origin**
Bedrockean

**Power**
Bedrock Break

**Notes**
The bedrock break ability doesn't work.

**Comment by QuantumXenon** [comment]
This is a known issue with the Forge version of Origins, but should be fixed in the next version
