### ISSUE TITLE
witherd fox keeps taking damage for no reason

### ISSUE THREAD

**Issue by CuteKitten8989** [QuantumXenon/origins-plus-plus#243]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version

I'm not sure how to figure that out tbh

**Origin**
Withered fox

**Power**
not sure
**Notes**
just starts taking damage and theres no stopping it

**Comment by QuantumXenon** [comment]
I was unable to replicate this issue using the latest version of Origins++ and dependencies. If you still experience the issue, please reopen this issue and attach logs
