### ISSUE TITLE
Technomancer Laser

### ISSUE THREAD

**Issue by NukularRandom13** [QuantumXenon/origins-plus-plus#244]
**Origin**
Which origin needs the balance?
Technomancer

**Power(s)**
Which power(s) need(s) to be balanced?

Laser

Mana Cap

**Balance Suggestion**
Do you have any ideas about how it could be balanced?

The laser barely ever registers that it hits things, even if its a straight shot with hitboxes showing to see that they hit, I guess I just want a way to make it function as a weapon better?

The Mana Cap is annoyingly low, if it were increased by even 50% i think the origin would be much more capable of competing with other origins.

**Comment by QuantumXenon** [comment]
The way the damage is done is a limitation of how the damage is calculated and done. Looking at the bottom of an entity is the best way to deal damage.

I have made some balance changes to (hopefully) make the Technomancer more competitive by altering the mana values for some powers and increase the rate of replenishing.
