### ISSUE TITLE
thornling boots and helmet do not work

### ISSUE THREAD

**Issue by wowdongle** [QuantumXenon/origins-plus-plus#245]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
fabric

**Versions**
minecraft version - 1.19.3
origins version - 1.8.1
Origins++ Version - 2.0+
- pekui - 3.7.7+1.14.4-1.20.1

**Origin**
thornling

**Power**
gold boots and gold helmet are not different when crafted with gold blocks
**Notes**
it still crafts gold items using gold blocks they just don't have the affect on them

**Comment by wowdongle** [comment]
it seems to not work in every version of origins plus plus too

**Comment by QuantumXenon** [comment]
This is a known issue which I believe to be an issue with Origins (Fabric) as it works as expected with Origins (Forge)
