### ISSUE TITLE
How do i use the keybinds

### ISSUE THREAD

**Issue by Crossalaxz** [QuantumXenon/origins-plus-plus#246]
this mod is great and all but its not fun when most of the key binds are not work or just not set so how do you use the keybinds for origins that have more than 3 things

**Comment by QuantumXenon** [comment]
What ModLoader and Minecraft version are you using?

**Comment by QuantumXenon** [comment]
Origins++ uses the following keybinds:
- Primary (default ‘g’)
- Secondary (default ‘unbound’)
- Load Toolbar Activator (default ‘c’)
- Save Toolbar Activator (default ‘x’)

**Comment by Crossalaxz** [comment]
how do you change them

**Comment by Crossalaxz** [comment]
<img width="961" alt="Screenshot 2023-08-10 at 1 13 47 PM" src="https://github.com/QuantumXenon/origins-plus-plus/assets/141879468/6b1e1609-805a-4a07-b852-3f10e86fc01c">

**Comment by Crossalaxz** [comment]
wich one

**Comment by QuantumXenon** [comment]
You have a mod that adds extra keybinds for Origins. The Primary and Secondary keybinds can be found there, but the other two can be found elsewhere in the controls menu
