### ISSUE TITLE
keybinds

### ISSUE THREAD

**Issue by BONEWEEVIL1** [QuantumXenon/origins-plus-plus#247]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge 

**Versions**
- 1.18.2
- 40.2.4
- [1.18.2] Origins Forge 1.5.0.1
- v2.0 [Forge]
- [[1.14.4 - 1.20.1] Pehkui 3.7.8

**Origin**
i think all from this mod

**Power**
most of them 

**Notes**
the keybinds are all almost on the primary

**Comment by QuantumXenon** [comment]
This is a known issue with the 1.18.2 version of Origins (Forge). There is a bug with it that prevents keybinds from working properly, so there isn’t anything I can be done until the fixes are backported (if they are)

**Comment by BONEWEEVIL1** [comment]
is there a way to fix it on my end like with an extra mod or something?
