### ISSUE TITLE
Flea cannot enter the nether portal without causing game to lockup

### ISSUE THREAD

**Issue by Xplodin** [QuantumXenon/origins-plus-plus#248]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge or Fabric?
Forge
**Versions**
1.19.2- Minecraft Version
43.2.21- Mod Loader Version
1.7.1.1- Origins Version
2.1.1- Origins++ Version
3.7.8- Pehkui Version

**Origin**
What origin is causing the problem?
Flea
**Power**
What power is causing the problem?
Im guessing its scaling when entering the nether portal
**Notes**
Include any other information that might be useful here
It locks the game up completely causing me to force close via task manager.
Steps: enter the nether through portal as flea, move a little bit around and watch everything lock up and halt

this has been reported to Pehkui as well here: https://github.com/Virtuoel/Pehkui/issues/429

no fix has been addressed yet

I tested with another small entity such as Insect, and that works fine

**Comment by QuantumXenon** [comment]
I tested this in a world with just Origins++ (and latest versions of dependencies) and I did not experience any issues, perhaps it is caused by another mod?

**Comment by Xplodin** [comment]
I forgot to mention this only happens server side
