### ISSUE TITLE
Artifacts mod

### ISSUE THREAD

**Issue by Turbulence72** [QuantumXenon/origins-plus-plus#249]
**Origin**
Demi-god

**Power(s)**
A raw diet

**Balance Suggestion**
There is an everylasting steak within the artifacts mod. There is both a cooked and raw variant. I was disappointed to find out i couldn't eat the raw variant

**Comment by QuantumXenon** [comment]
This is something I do not plan to support directly with Origins++, rather with the [compatibility datapack](https://github.com/QuantumXenon/origins-plus-plus-modded-support). There is not currently support for Artifacts, but I may add it in the future.
