### ISSUE TITLE
Origin changes everytime i respawn

### ISSUE THREAD

**Issue by itsSBhere** [QuantumXenon/origins-plus-plus#250]
Fabric

- Minecraft Version 1.19.2
- Origins++ Version 2.1.1

What origin is causing the problem?
any

Include any other information that might be useful here
im not sure if its intended to or if it can be turned off but any time i die i get respawned as a random origin

**Comment by QuantumXenon** [comment]
Do you also have a mod called ‘Origins Randomiser’ installed?

**Comment by itsSBhere** [comment]
if it was in the modpack then i would assume yes. but i havent like added it myself. ill look into it

**Comment by QuantumXenon** [comment]
The Origins++ modpack has that mod in it. You can remove it if you do not want that feature
