### ISSUE TITLE
keybinds issue 

### ISSUE THREAD

**Issue by BONEWEEVIL1** [QuantumXenon/origins-plus-plus#251]
Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report

Loader
Forge

Versions

1.18.2
40.2.4
[1.18.2] Origins Forge 1.5.0.1
v2.0 [Forge]
[[1.14.4 - 1.20.1] Pehkui 3.7.8
Origin
i think all from this mod

Power
most of them

Notes
the keybinds are all almost on the primary

is there a way for me to fix this on my end or am i just stuck with it, tell it get or if it get pack ported

**Comment by QuantumXenon** [comment]
This is a known issue with Origins (Forge). The only way for this to be fixed is for the bug to be fixed by backporting the fix to 1.18.2. I don’t know if this will be done, but I have seen many people report it so it may be done.
