### ISSUE TITLE
Please add a wetness meter for the Jellyfish

### ISSUE THREAD

**Issue by dizzsea** [QuantumXenon/origins-plus-plus#252]
I've been playing the Jellyfish and it's pretty fun. I can understand why the drying-out mechanic was implemented, but it would be so much more tolerable if I could actually tell _when_ I'm drying out. 

The only real way to tell is when I take damage out of nowhere. Sometimes I start drying again moments after I get in water, while other times I will be fine for several minutes until I dry out again. I seriously cannot tell if the wetness is something that regenerates as I am in water, or returns to full instantly. 

A meter for this would really clear the confusion and make the origin a lot more manageable to play. I seriously don't understand why there isn't one when there are meters for several things of other origins.

**Comment by QuantumXenon** [comment]
I have reworked the dryness mechanic so that there is a bar which depletes when outside of water and replenishes when inside of water. The Jellyfish starts to take damage when the bar is empty, which can be stopped by getting wet again.
