### ISSUE TITLE
1.18.2 Keybinds

### ISSUE THREAD

**Issue by GiraffeLif** [QuantumXenon/origins-plus-plus#254]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- minecraft 1.18,2
- Mod Loader 40.2.4
- Origins 1.4.1.4
- Origins++ 2.0
- Pehkui 3.7.8

**Origin**
any with 2 keybind keys

**Power**
any with keybinds

**Notes**
so any origin that has 2 powers with keybind all come up as only the primary key and when trying it all power acivate with only primary break alot of the origins

**Comment by QuantumXenon** [comment]
This is a known issue with Origins (Forge) on 1.18.2, so unless there is a backport for the keybind fix introduced in 1.19.2, this will continue to happen.
