### ISSUE TITLE
Giant piggyback

### ISSUE THREAD

**Issue by YevhenHoina** [QuantumXenon/origins-plus-plus#256]
Using Forge 

Minecraft Version: 1.19.2
Mod Loader Version: 43.2.8
Origins Version: 1.19.2-1.7.1.2
Origins++ Version: 2.1.1-forge
Pehkui Version: 3.7.8+1.19.2-forge

Giant's piggyback allow me to pick up creatures they are pretend to be thrown (staying on my head and take fall damage) after that stay on my head until despawn even if I try to throw them again.

**Comment by QuantumXenon** [comment]
Merging with #236
