### ISSUE TITLE
Automaton - Running out of steam does not kill you after a minute

### ISSUE THREAD

**Issue by FPeely** [QuantumXenon/origins-plus-plus#257]
**Loader**
Forge

**Versions**
- Minecraft Version - 1.19.2
- Mod Loader Version - 43.2.21
- Origins Version - 1.7.1.1
- Origins++ Version - 2.1.1
- Pehkui Version - 3.7.8

**Origin**
Automaton

**Power**
Running out of steam does not kill my character after waiting for a while, having to get buckets from creative or from a friend to not get softlocked.

**Notes**
My character cannot be killed with /kill either.

**Comment by QuantumXenon** [comment]
This has been reworked for a better and more balanced experience. There is now a bar, which if empty kills you. It depletes when you have no steam, and replenishes when you do.
