### ISSUE TITLE
Can't find any versions before 1.5 (sorry if this is the wrong way to ask a question! I couldn't find any socials on the page to DM..)

### ISSUE THREAD

**Issue by Zrecao** [QuantumXenon/origins-plus-plus#258]
Hi, do you guys have the versions before 1.5? I remember the enigma's phase used to teleport you randomly, and I really liked that mechanic, but it doesn't seem to be in the current version. If possible, I'd really love if you guys had the previous versions so I can get the old phase back. A standalone power file also works so I can replace the phase with that.

I'm really sorry if this isn't the correct place to submit questions..

**Comment by QuantumXenon** [comment]
If you go to https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus/files and scroll down to the bottom or go to the second page, you should be able to find older versions.
