### ISSUE TITLE
Pixie rework or new origin

### ISSUE THREAD

**Issue by Fl414r** [QuantumXenon/origins-plus-plus#260]
**Origin**
Pixie

**Power(s)**
Flying, climbing and Boost

**Balance Suggestion**
At the moment Pixie is literally a spider with elytra. What about this (https://origination.gitbook.io/origination-1.19.2/origins-information/list-of-playable-origins/fairy) variation? Origination version of this Origin also have a bug and Fairy cant deal any crits, that can be good weak power.
At least block fireworks, but add normal jumps, remove climbing and increase boost. At maximum rework Pixie completely or add Fairy as another Origin. 
Oh, and the pickup range is completely broken, sometimes I can't get an item within a millimeter of it.

**Comment by QuantumXenon** [comment]
I've made the simpler changes that you have suggested, which will be included in the next update. If you find those are insufficient, I can look at a larger rework of the origin.
