### ISSUE TITLE
Shadow Origin

### ISSUE THREAD

**Issue by PenginKami** [QuantumXenon/origins-plus-plus#263]
**Origin**
Which origin needs the balance?

**Power(s)**
Shadow Storage
Shadow Snack
Shadow
Weak
The Weakness of the Sun / Shadow Form

**Balance Suggestion**
Do you have any ideas about how it could be balanced?
I'll start with an explanation, currently shadow stands out to me as the best origin in origins ++, there are multiple origins with the same abilities/similar or same concept and have way, way more drawbacks. (Think shadow crawler, voidling and spectre.)

Shadow storage: Change to enigmas "Behind you" Power

Reason 1: Thematically speaking, I feel it's a lot more fitting to have a power where you exit someones shadow, hence appearing behind them.
Reason 2: Shadow's kit is already great, and having extra soulbound inventory slots is just adding more powerful utility skills onto an origin with an already amazing utility skill.

Shadow snack: Remove regeneration - Make it cost shadow points to use.

Reason 1: Being at full hunger heals you, so the added regeneration is a bit insane.
Reason 2: Currently the ability is spammable with zero risk, or loss. Isn't it a bit powerful to just, not need to eat AT ALL?

Weak: 7 > 6 hearts

Reason 1: Currently shadow can just go underground if low on health, and stay there for a very long time, it's difficult to be killed when you can press a button and enter spectator mode, whilst also being one of the fastest moving origins whilst phasing makes it even more difficult to be killed in pvp. 
Reason 2: Spectre, one of the only characters who can match shadow's level of mobility requires it to drain it's health over about 6 seconds, for a short duration of phase & creative flight. This is difficult to do as spectre has only 5 hearts, meaning you have to either gain spectre points whilst you're not in danger, or risk dying when setting yourself to 4 hearts or below. Basically, if spectre has to do all that, I dont see why shadow just has to stay underground for a short period for a long duration.

Shadow: Wearing any armor that isn't light should disable JUST this ability as well.

Reason: Another zero risk ability, the playstyle of a shadow should encourage being a shadow, and loud clanky heavy armor isn't that sneaky to wear.

The Weakness of the Sun / Shadow Form: adding - no longer gain shadow points whilst in the sun, and also burn in the sun, when you're in the light you're forced to exit shadow form.

Reason 1: For thematical & balance reasons I feel this is fair when looking at the origins I mentioned at the top and their cons, as well as other origins in the roster.

Reason 2: Currently shadow is an origin that doesn't have a playstyle, it's simply free spectator mode and never eat food again. It's something anyone could pick up like a level 1 origin, if it's going to be a tier 3 it should have a playstyle attached, and help players who already enjoy that playstyle normally of living underground and being sneaky, whilst hindering those who don't play the game that way. 

Reason for the "forced to exit shadow form." I think this single change is probably the most important here and if I could choose one change, it'd be this. This is what makes it into a interesting way to play the game. Making underground tunnels, observing people from the shadows as being in the light would expose you, and being careful not to accidentally fly too close to lava, all of this gives the ability a very interesting and appealing drawback, which enhances the experience of playing the origin even though it's a drawback. This turns it from the ability of spectator mode, to becoming a shadow, a being who can travel anywhere quickly, as long as it's in the shadows.

As a little thing at the end, please change the background of the meter to white so you can see how much charge you have on it's ability, it's like trying to see how many you hearts when you have wither currently.

**Comment by QuantumXenon** [comment]
I've made these changes, which will be available in the next update
