### ISSUE TITLE
Rift Walker

### ISSUE THREAD

**Issue by PenginKami** [QuantumXenon/origins-plus-plus#264]
**Origin**
Rift Walker

**Power(s)**
Which power(s) need(s) to be balanced?
Aurophilia
and portality (kinda?)

**Balance Suggestion**

It's the origin I play the most as, and I'm in love with it, but the rift is very underwhelming in its range, I honestly just use divine architect instead since its phase/float combo has a good enough duration where I can use it when I want to, and then I can use it wherever I want unlike rift mage who's confined to a small area.

I suggest adding a passive:
When your rift is located near a beacon/ (on one?), increase its range is significantly increased (or if it's possible, by the range of the beacon with its tier.)
"The beam of a beacon prevents you from getting lost within the rift, whilst also giving the strength to go further."

It'd be good to replace Aurophilia with the new passive as Aurophilia makes little sense thematically and as a power, I don't see anything at least with its lore that ties it into the origin, or even it's playstyle for that matter. And then the power itself is replaced by a fortune one iron pickaxe.

Counter I can't fairly judge right now with it not working, but since it's (I'm assuming, specific to ender pearls in multiplayer) adding an extra passive for pve like making mobs glow would be nice.

I find it annoying that I can't use pressure plates & nether portals in my home as a rift walker, since the phase makes you go through them, so maybe letting it toggle your rift phasing instead would be good too.

and as a last possible passive, to make it equal to other origins that provide phase/float & sometimes even night vision.
Consuming an eye of ender gives you night vision for 20 minutes.
(Or possibly, just night vision within the rift might work)

Extra thing, make the "you are venturing too far from your rift" text red, so it's more visible.

**Comment by QuantumXenon** [comment]
I've made these changes, which will be available in the next update
