### ISSUE TITLE
Ice-Based Origin Crash

### ISSUE THREAD

**Issue by Chairrator** [QuantumXenon/origins-plus-plus#270]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

Forge

CurseForge

**Origin**
All Ice Based Origins (minus the IceKing)

Spawning into and selecting any of the ice or snow based origins automatically causes a crash, with the inability to log back into said world. Tried selecting human before changing to any of the specified origins, still crashed. Tried spawning in an ice biome, still resulted in a crash.

**Comment by QuantumXenon** [comment]
Could you provide more information? I have done some testing and was not able to reproduce the issue. Do you have the latest version of all dependencies?

**Comment by QuantumXenon** [comment]
Furthermore, the latest version of Origins (Forge) has extra measures taken to resolve issues with special spawn points. If you still have issues after updating, please reopen this issue and include logs.
