### ISSUE TITLE
Help compatibility

### ISSUE THREAD

**Issue by tipp3** [QuantumXenon/origins-plus-plus#272]
Hello, I'd like to add your mod to Life in the village 3. 

could you help me achieve that ? it keeps crashing my server.

**Comment by QuantumXenon** [comment]
Could you send a log?

**Comment by tipp3** [comment]
[crash-2023-09-21_20.19.44-fml.txt](https://github.com/QuantumXenon/origins-plus-plus/files/12701846/crash-2023-09-21_20.19.44-fml.txt)

**Comment by tipp3** [comment]
I can copy past if you want

**Comment by QuantumXenon** [comment]
You need to install [Caelus API](https://www.curseforge.com/minecraft/mc-mods/caelus) for Origins (Forge) to work

**Comment by tipp3** [comment]
I did

**Comment by QuantumXenon** [comment]
Can you double check? The log says `Failure message: Mod apoli requires caelus 1.18.1-3.0.0.2 or above. Currently, caelus is not installed`

**Comment by tipp3** [comment]
I added theese to the modpack : 

caelus-forge-1.19.2-3.0.0.6

origins-forge-1.19.2-1.7.1.3-all

origins-plus-plus-2.1.2-forge

Pehkui-3.7.8+1.19.2-forge

xlpackets-1.18.2-2.1

**Comment by tipp3** [comment]
it works just fine in single player but crash the serv

**Comment by QuantumXenon** [comment]
Is that crash log from after you added those mods?

**Comment by tipp3** [comment]
yeah

**Comment by QuantumXenon** [comment]
Hmm, I don’t know why it says it’s not installed if you’ve added it. Perhaps, try removing and adding them again on the server

**Comment by tipp3** [comment]
I'll try for the third time ig

**Comment by QuantumXenon** [comment]
Can you also send the standard log, maybe there’s something there that can help

**Comment by tipp3** [comment]
what do you mean standard log ?

**Comment by QuantumXenon** [comment]
the latest.log file in the logs folder

**Comment by tipp3** [comment]
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/12704856/latest.log)

**Comment by QuantumXenon** [comment]
Sorry for the late reply! The only thing I can see of note in the crash log is
```
Failure message: Mod apoli requires caelus 1.18.1-3.0.0.2 or above
Currently, caelus is not installed
```
I know you said you have `caelus` installed, but if that's the case, I don't know what else you could do to try and get it to work.
