### ISSUE TITLE
One Key for all abilities

### ISSUE THREAD

**Issue by JostinSusa** [QuantumXenon/origins-plus-plus#275]
**Loader**
Forge

**Versions**
- Minecraft Version: 1.18.2
- Mod Loader Version
- Origins Version: 1.4.1.4 unified
- Origins++ Version: 2.0 beta
- Pehkui Version: 3.7.8

**Origin**
All origins

**Power**
All Powers

**Notes**
We cannot set one key for each skill, we can only set one key to use all skills, so some origins have problems with their important skills, such as ghost mode, endertransport, etc. We can only set one key.

**Comment by QuantumXenon** [comment]
This is a known issue with Origins (Forge) on 1.18.2
