### ISSUE TITLE
Keybind Issue (there arent enough keybinds for all the abilities)

### ISSUE THREAD

**Issue by CloudyKi** [QuantumXenon/origins-plus-plus#278]
**Loader**
Forge

**Versions**
- Minecraft Version - 1.18.2
- Mod Loader Version - Forge 40.2.0
- Origins Version - 1.18.2-1.4.1.4
- Origins++ Version - 2.0 forge
- Pehkui Version - 3.7.8

**Origin**
Its not tied to a specific origin, it affects ALL origins

**Power**
Any power will cause this issue

**Notes**
For example the origin I chose was the "devine architect" and this origin as more than two abilities. When I press my "Active Power primary" button, it actives all of my abilities at the same time, causing me to fly, phase, and shoot a projectile all at the same time. Going into the settings, there are only two keybinds to set, primary and secondary. however the secondary power does nothing when bound to a key. The only keybind that works is the primary power, and it activates all my powers instead of just one. There is no were else in the settings with more keybinds for this mod. We added this to a custom mod pack but the problems still persist even when launching the mod on its own

The same happens with my friends who are each using a different origin. They will press their primary button and it will activate ALL of their abilities at the same time.

This can be frustrating for a lot of people who want to use their abilities cause they arent able to specifically choose which abliity to use, it just uses all of them. I cannot use my abilities at all because it just makes me fly, shoot, and phase. I cant JUST shoot or JUST fly.

I think there might be a problem with the Origins + + in the sense that there needs to be more keybinds added. Not only that but the problem with ALL of the abilities going through ONE key needs to be fixed, and have each abilitiy only bound to one key.

I dont know ANYTHING about coding or mod making so its probably way more complicated, but as of right now its bugged and its tainting the experience of me and my friends. We are also launching an SMP soon and we would like for this to be fixed so everyone can have fun

**Comment by QuantumXenon** [comment]
This is a known isssue with Origins (Forge), so until that is f

**Comment by CloudyKi** [comment]
do we know when that will be fixed? cause we cant update to a newer version of origins due to the rest of the modpack. The smp is gonna be live for a while with a lot of people so  we were hoping this could have been fixed

**Comment by NinaKonecna** [comment]
I've found a workaround, if you're still interested.

I'm not sure if this will work for you cause it's kinda janky but when I installed origins plus plus, but the fabric one, version 1.5.3 (minecraft version 1.18.2), and also installed xlpackets for fabric version 3.1 (minecraft version 1.18.2), I could get the keybinds to work, it has some bugs as this is not how it is intended to be used (such as player height not being scaled when they die, though that can be fixed by commandblocks) but it still worked out for me and made the mod playable in 1.18.2
