### ISSUE TITLE
Not enough keybinds

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [QuantumXenon/origins-plus-plus#279]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- Minecraft Version - 1.20.1
- Mod Loader Version - 0.14.22
- Origins Version - 1.10.0
- Origins++ Version - 2.2
- Pehkui Version - 3.7.8

**Origin**
Enigma and a bunch of others, too

**Notes**
Many Origins like the Enigma do have 3 activated abilities. One of them is never usable because there is only 2 Key-binds in the options menu, not 3. This leads to the problem, that a huge amount of origins can't use important abilities like "Behind You".

**Comment by QuantumXenon** [comment]
The additional abilities should be bound to either `Save Toolbar Activator` or `Load Toolbar Activator`

**Comment by Terandox-The-Pineapple** [comment]
And how do trigger Save `Toolbar Activator`?... I don't know what key that is supposed to be

**Comment by QuantumXenon** [comment]
That should be `c` by default - it is a keybind for creative mod, so it will be in a different place in controls, but it should still work

**Comment by Clinkr1000** [comment]
this is not fixed. i even installed 'Origins Extra Keybinds'. Nothing worked. using `save toolbar activator` does nothing for skills bound to it.
