### ISSUE TITLE
[Feature Request] A New GUI to choose origins

### ISSUE THREAD

**Issue by Snapshotlight** [QuantumXenon/origins-plus-plus#281]
As the original Origins mod has only serveral origins to choose, it is fast and convenient to choose one of the origins by just clicking. However, origin++ gives hundreds of origins making choosing origin exhausting and time-wasting.
I think it may be better if the GUI is changed.
Adding a search bar and the amount of origins that can be displayed on one screen will be a possible solution.

**Comment by QuantumXenon** [comment]
Thanks for the suggestion! I don't plan on adding anything like that into Origins++ directly as it would make it complicated to manage multiple Munecraft versions. You could try this mod here instead though: https://modrinth.com/mod/altorigingui
