### ISSUE TITLE
just read the comment

### ISSUE THREAD

**Issue by Jolteon1234amongus** [QuantumXenon/origins-plus-plus#285]
When I launch the game it says "Mod origins_plus_plus requires xlpackets 1.18.2-2 or above", but when I tried to download xlpackets it isn't on 1.20.1 which is what version of origins++ mod I am using. Please fix this.

**Comment by QuantumXenon** [comment]
The latest version of XL Packets should work, even though it isn’t marked as compatible

**Comment by QuantumXenon** [comment]
Please reopen this issue if that doessn't solve your issue
