### ISSUE TITLE
Light Mage bug

### ISSUE THREAD

**Issue by BoltsRolow** [QuantumXenon/origins-plus-plus#288]
**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
Light Mage

**Power**
The Snow Golem summoning ability is currently attached to the clock when its intended to be on the Carved Pumpkin
and the Speed ability isn't on the clock.

**Comment by QuantumXenon** [comment]
This should be fixed in the next version
