### ISSUE TITLE
Withered Fox power usefulness + flight

### ISSUE THREAD

**Issue by Exsiq** [QuantumXenon/origins-plus-plus#29]
Hi. The Withered fox origins wither skull is now pretty useless because it has a like 30 second cooldown. I feel that the origin should have a 5 to 10 second cooldown instead. Also, the flight feature is pretty bugged. The flight cooldown never runs out, and you can just keep flying infinitely. It also means that you can't jump normally as withered fox because of the flight. I'm not 100% sure if it's an intended feature or not but to me it feels like a bug.

**Comment by QuantumXenon** [comment]
Replacing jumping with floating is intended, but I am working on a fix to the infinite flight. I have also adjusted the cooldown.
