### ISSUE TITLE
Error on startup to server: "Internal Exception: io.netty.handler.codec.EncoderException: Failed to decode: Not a string, Not a list 

### ISSUE THREAD

**Issue by Nariod14** [QuantumXenon/origins-plus-plus#290]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge or Fabric?
Forge
**Versions**
- Minecraft Version
- 1.19.2
- Mod Loader Version
- 43.2.14
- Origins Version
- 1.7.1.3
- Origins++ Version
- 2.2
- Pehkui Version
- 3.7.8

**Origin**
It's not really any origin but rather I'm getting an error whenever I try to connect to my minecraft server. A screenshot of the error in question and the latest logs of my client are included. I only thought to put up an issue here because I saw your mod's name in the error so I'm not entirely sure whether its really this mod that caused it. Any help would be greatly appreciated!

**Power**
N/A

**Notes**
Attatchments:
![image](https://github.com/QuantumXenon/origins-plus-plus/assets/21109756/1b83937b-24b2-4448-adfd-8a616b44edee)
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/13063863/latest.log)
[server.log](https://github.com/QuantumXenon/origins-plus-plus/files/13063866/server.log)

**Comment by QuantumXenon** [comment]
Are you still having the issue, or is it working now with newer mod versions?

**Comment by Nariod14** [comment]
Not having the issue anymore because I abandoned that server for a while, a while ago. I've since started a new modpack on 1.20.1and I'm having no issues now.
