### ISSUE TITLE
Crash Report, World Loading Error

### ISSUE THREAD

**Issue by AlphaTheYveltal** [QuantumXenon/origins-plus-plus#297]
**Loader**
Forge

**Versions**
1.20.1
Forge 47.2.0
1.10.0.2
2.2-Forge
3.7.11

While loading a world on Cheats On Survival, the display for the origins will not show. With a chance of crashing when using Large Biomes. I have done testing to root out the issues and when removing this mod when using the same settings and just using the Origin mod causes no issues, but the issues arise when using Origins++. I do not know exactly why this is happening - however this is extremely irritating when trying to test things and this is the first thing that happens.

**Comment by QuantumXenon** [comment]
Sorry for the delayed response - Could you provide a log?

**Comment by AlphaTheYveltal** [comment]
No worries at all, haven't really been able to do much myself due to the holiday season. I went to go try and get it again and it just somehow began working - as it probably was a fault on the Origins (Forge) mod itself and not relating your mod. Apologies on such.

It updated 2 days ago for this version on Forge and it just began to work. I am sorry for the inconvenience or worry this could have caused!

**Comment by QuantumXenon** [comment]
Great! I'm glad it's working now
