### ISSUE TITLE
Goolien and Broodmother

### ISSUE THREAD

**Issue by niipnuum** [QuantumXenon/origins-plus-plus#30]
**Version**
Fabric

**Origin**
The origin(s) that is affected by the problem: Goolien and Broodmother

**Power**
The power is the problem

**Notes**
Broodmother: The webs that spawn when you do a melee attack against an entity don't de-spawn and could become a hassle
Goolien: Cannot eat anything, no meat or vegetables. I have tried.

**Edit/Notes**
For the Goolien you can sometimes eat, however all food items eventual goes back to being 'inedible'. I am always on full health this bug happens and I don't know if that factors into it.

**Comment by QuantumXenon** [comment]
For the Goolien, eating is supposed to directly replenish health instead of filling your hunger bar. Though this may be a bit confusing, so I will look into a better way of implementing it

**Comment by QuantumXenon** [comment]
I think I've fixed the Goolien. I have also partly fixed the Broodmother, but I am still working on it
