### ISSUE TITLE
Devine Architect can't tame wolves

### ISSUE THREAD

**Issue by SociallyAwkwardWolf** [QuantumXenon/origins-plus-plus#305]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

Fabric

**Versions**
- Minecraft Version: 1.20.1
- Mod Loader Version: 0.14.23
- Origins Version: 1.20.1
- Origins++ Version: 2.2
- Pehkui Version: 3.7.8

**Origin**
What origin is causing the problem?
Devine Architect

**Power**
What power is causing the problem?
None?

**Notes**
Include any other information that might be useful here
I just can't tame wolves. I don't know if its a feature but it isn't mentioned

**Comment by QuantumXenon** [comment]
This is part of the 'Distrust' power, so it is part of the origin's design. I apologise if the wording was unclear
