### ISSUE TITLE
Petrified hearts doesnt drop as Deathsworn

### ISSUE THREAD

**Issue by JulianIsFree** [QuantumXenon/origins-plus-plus#306]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version 43.3.0
- Origins Version 1.7.1.3-all
- Origins++ Version 2.2
- Pehkui Version 3.7.11

**Origin**
Probably origins++

**Power**
Petrified hearts doesnt drop, tried it on fabric - all works just fine

**Notes**
Instlaed:
Origins Classes 1.2.0
Origin Strictly v6.1

**Comment by QuantumXenon** [comment]
This is a known issue with Origins (Forge) itself, so there isn't anything I can do about it, and it has been reported to the developers

**Comment by JulianIsFree** [comment]
> This is a known issue with Origins (Forge) itself, so there isn't anything I can do about it, and it has been reported to the developers

can you please provide a link? im really interested in trying to debug this :) issue context would be helpful
