### ISSUE TITLE
Enigma can accidentally destroy Create entities by looking at them

### ISSUE THREAD

**Issue by AWoodward96** [QuantumXenon/origins-plus-plus#308]
**Loader**
Forge 

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: Forge 43.3.5
- Origins Version: 1.19.2-1.7.1.3-all
- Origins++ Version: 2.2-forge
- Pehkui Version: 3.7.11+1.19.2-forge

- Create Version: 1.19.2-0.5.1

**Origin**
Enigma

**Power**
Staring Contest

**Notes**
Up to ya'll to determine if this is a bug or not, but the Enigma can instantly destroy Create machines if you stare at them for too long. To test, just set up a Mechanical Bearing with a block on top, add power to it, turn it on, and look at it for 10s. Create mod contraptions can get huge, so the hitbox's on them can become difficult to avoid staring at, so it'd be nice if this was fixed.

**Comment by QuantumXenon** [comment]
Merging with #276
