### ISSUE TITLE
Most origins not offered

### ISSUE THREAD

**Issue by nightlocust** [QuantumXenon/origins-plus-plus#309]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge or Fabric?

**Versions**
- Java 1.20.2
- Fabric for 1.20.2
- Origins 1.20.2-1.11.3
- Origins++ v2.2
- Pehkui 3.7.11+1.14.4-1.20.2

**Origin**
N/A, problem occurs before picking an origin.

**Power**
N/A, problem occurs before picking an origin.

**Notes**
I booted up a singleplayer world, excited to try the new origins, and it only offered me 10 of the hundred options professed in the mod. I wanted to play the Iceking, but it is not offered. What gives? Is there an issue in the config settings?

**Comment by QuantumXenon** [comment]
Merging with #314
