### ISSUE TITLE
Gui not showing up

### ISSUE THREAD

**Issue by derp3409** [QuantumXenon/origins-plus-plus#310]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge or Fabric? Forge

**Versions**
- Minecraft Version 1.20.1
- Mod Loader Version Forge 47.2.17
- Origins Version 1.10.0,4
- Origins++ Version 2,2
- Pehkui Version 3,7,11

**Notes**
The starting gui does not appear when starting a new world, i've tried using the command "/origin gui" and it does not appear as well. I've tried setting the origins with "/origin set" but it does not work as well, all i can do to acces the origins is the command "/origin random"

**Comment by wraino** [comment]
mine is not working too, when i joined doesnt appeared the GUI, i tried many things but nothing

**Comment by QuantumXenon** [comment]
Merging with #350
