### ISSUE TITLE
XL Packets

### ISSUE THREAD

**Issue by R0SSW00DP4RK** [QuantumXenon/origins-plus-plus#311]
You should be able to use the most recent version (even though it isn't marked as compatible). If that doesn't help, please reopen this issue

_Originally posted by @QuantumXenon in https://github.com/QuantumXenon/origins-plus-plus/issues/302#issuecomment-1846154137_

Couldn't re-open the issue for some reason, meaning I had to create a new issue instead.

Anyways, still having an issue but it isn't with Origins++ now. Tried to add Origins++ to Aternos on Forge (MC 1.20.1) and it was coming up with XL Packets was required (can't add it due to it being outdated), when I don't think it is. Now you're wondering why I've come here, which is because Aternos really said "Contact the mod creator!"
So is there anything you can actually do or has Aternos Support sent me on a wild goose chase?

**Comment by QuantumXenon** [comment]
Sorry for the late reply, but XL Packets should now be marked as compatible for 1.20.1 on Fabric and Forge
