### ISSUE TITLE
[Giant] Player doesn't sleep in the center of the bed.

### ISSUE THREAD

**Issue by Knaikki** [QuantumXenon/origins-plus-plus#313]
Mundane issue that I'm unsure of being a mod incompatibility or with Origins++.

**Loader**
Fabric

**Versions**
- Minecraft : 1.20.1
- Fabric Loader : 0.15.1
- Origins : 1.10.0
- Origins++ : 2.2
- Pehkui : 3.7.11

**Origin**
Giant

**Power**
Gigantic Bed

**Notes**
Thank you for your time.

https://github.com/QuantumXenon/origins-plus-plus/assets/153880300/22c1a4a0-f678-48e8-989d-bbed099e894c

**Comment by QuantumXenon** [comment]
This is a limitation of how the origin can be implemented without additional rendering changes, as such I don't plan to fix this issue. Thank you for the report though!
