### ISSUE TITLE
Dark Mage mana potions

### ISSUE THREAD

**Issue by DarthPurple** [QuantumXenon/origins-plus-plus#316]
The dark mage mana potions are not working at all I tired using honey and offhand aswell as using mane while holding honey in my left hand but still died. Is this a bug or am I doing something wrong?

**Comment by QuantumXenon** [comment]
I'm not sure why that isn't working for you. Your description seems correct and I was able to successfully make mana potions while testing using the same method. Could you try and see if it works now for you?
