### ISSUE TITLE
Rat origins does not provide night vision

### ISSUE THREAD

**Issue by stef1904berg** [QuantumXenon/origins-plus-plus#319]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version: 1.20.1
- Mod Loader Version: 47.2.18
- Origins Version: 1.20.1-1.10.0.5
- Origins++ Version: 2.2-forge
- Pehkui Version: 3.7.12+1.20.1-forge

**Origin**
Rat

**Power**
Rats Eyes
Description of the power suggests that the power provides night vision, or at least a version of it. However, changing between Human origin (Origin base mod) and the Rat origin does not change anything about the visibility. 

**Notes**
Looking at the rats_eyes.json power, it gives a 0.4 night vision when not submerged in water. ~~It might be that 0.4 is an invalid strength, as giving yourself 0.4 night vision doesnt work (using commands).~~ I was wrong, the origins mod allows for a lower night vision effect.

**Comment by QuantumXenon** [comment]
Sorry for the late reply - could you please check to see if you still have the issue. There was a noticeable difference for me in testing
