### ISSUE TITLE
Binturong camouflage not working

### ISSUE THREAD

**Issue by Zegamertrik** [QuantumXenon/origins-plus-plus#325]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version : 1.20.1
- Mod Loader Version : 47.2.0
- Origins Version : 1.10.0.5
- Origins++ Version : 2.2
- Pehkui Version : 3.7.12

**Origin**
Binturong

**Power**
Camouflage

**Notes**
When activating camouflage only the outer layer of my skin becomes invisible
# with the cape if off without it is on
![2024-01-12_18 18 34](https://github.com/QuantumXenon/origins-plus-plus/assets/116988545/5e40f4c8-9f39-4d8b-a258-d68a11b4f138)
![2024-01-12_18 18 31](https://github.com/QuantumXenon/origins-plus-plus/assets/116988545/7369959b-5cb1-4b46-8bb2-0ec2547ab37c)

**Comment by QuantumXenon** [comment]
This seems to be an issue with Origins (Forge) as I can't reproduce the issue in testing on Fabric
