### ISSUE TITLE
Does not work with Bucolic Origins

### ISSUE THREAD

**Issue by Gremdas** [QuantumXenon/origins-plus-plus#327]
I really wanted to launch it together with Bucolic Origins. But when you try to do this, a gray screen appears, and after that the game closes with the inscription "incorrect player data". Is there any way to fix this?
![javaw_5RsmJk6nYo](https://github.com/QuantumXenon/origins-plus-plus/assets/157073291/036d8338-3c70-43f0-ba66-4b61975c10b6)

**Comment by Gremdas** [comment]
![изображение_2024-01-19_015830445](https://github.com/QuantumXenon/origins-plus-plus/assets/157073291/7236977a-d830-4e3e-8b6f-c9960dc5adaa)

**Comment by Gremdas** [comment]
Version Fabrick

**Comment by QuantumXenon** [comment]
This is probably caused by the packets becoming too large - try installing a packet enlarging mod, such as XL Packets Fabric and see if that helps
