### ISSUE TITLE
I am not able to damage any mobs unless I am flying, or I crit the mobs.

### ISSUE THREAD

**Issue by Rouxir** [QuantumXenon/origins-plus-plus#328]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
- Fabric

**Versions**
- Minecraft Version 1.20.1
- Mod Loader Version 1.20.1
- Origins Version 1.20.1-1.10.0
- Origins++ Version 2.1.2 1.20.1
- Pehkui Version 3.7.8+ 1.14.4- 1.20.1

**Origin**
What origin is causing the problem? Birb

**Power**
What power is causing the problem? A damage problem

**Notes**
Include any other information that might be useful here - You can’t deal damage.

**Comment by QuantumXenon** [comment]
Merging with #294
