### ISSUE TITLE
Devine architect dimensional traveler

### ISSUE THREAD

**Issue by Dooglesz** [QuantumXenon/origins-plus-plus#334]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version forge 43.3.7
- Origins Version 1.7.1.13 (forge)
- Origins++ Version 2.2 (forge)
- Pehkui Version 3.7.11

**Origin**
Devine architect

**Power**
Dimensional traveler (nether)

**Notes**
power is not bound to any key and i can't find where to bind it

**Comment by QuantumXenon** [comment]
The keybinds are:
- Nether: `Save Toolbar Activator` (default `c`)
- End: `Load Toolbar Activator` (default `x`)
