### ISSUE TITLE
casting wrong spells

### ISSUE THREAD

**Issue by piggylittle** [QuantumXenon/origins-plus-plus#335]
forge version
origins++
light mage is the issue

I have secondary spells to my primary and secondary abilities. They need something in my offhand, such in this case a clock to cast Haste, which gives speed and mining haste. But instead it summons snow golems from the Army spell which should be a carved pumpkin in my offhand.

**Comment by QuantumXenon** [comment]
Fixed in https://github.com/QuantumXenon/origins-plus-plus/commit/cf26eec408e38c532434f04d1a5820bb098d9858
