### ISSUE TITLE
Lost draconian teleporting

### ISSUE THREAD

**Issue by The-Beloved10** [QuantumXenon/origins-plus-plus#337]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Fabric?

**Versions**
- Origins++ Version

**Origin**
Lost Draconian

**Power**
When using the secondary power, teleporting short distances, anyone who is also a lost draconian will be teleported to the person who used the 2ndary power.

**Notes**
People who used to be a lost draconian and have changed their origin will still be teleported to the person who is a lost draconian and used the teleport power.

**Comment by QuantumXenon** [comment]
Merging with #371
