### ISSUE TITLE
Error when joining server : Payload may not be larger than 1048576

### ISSUE THREAD

**Issue by tx5i** [QuantumXenon/origins-plus-plus#341]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge 

**Versions**
- 1.20.1
- Mod Loader Version
- 1.10.0
- 2.2
- 3.7.12

Internal exception: io.netty.handler.codec.decoderexception: java.lang.illegalargumentexception: payload may not be larger than 1048576

**Notes**
So, I decided to add origins++ to the medieval mc - mmc2 by shxrkie modpack and well the packets are too much and it has badpackets & packetfixer so is there a way to fix this?
![image](https://github.com/QuantumXenon/origins-plus-plus/assets/148471947/8b27f88a-27ba-4c03-8dcb-2153e4102257)

Also "[XL Packets Renewed](https://www.curseforge.com/minecraft/mc-mods/xl-packets-renewed)" isn't on 1.20.1

**Comment by DarkMage303** [comment]
i fixed the issue by installing the base XL packets, and the Connectivity mod

**Comment by QuantumXenon** [comment]
This can be fixed by installing a packet enlarging mod, such as the one suggested by @DarkMage303, or other similar mods
