### ISSUE TITLE
Spectre Origin

### ISSUE THREAD

**Issue by Pendantrapier30** [QuantumXenon/origins-plus-plus#342]
Fabric Loader

Origins ++ version

**Origin**
Spectre

**Power**
"Soul devouerer: This was once a holy ability used to smite demons, but the curse has corrupted it into a sinister form. Devour the souls of your enemies on hit."
Hitting enemies does fill the soul meter

**Comment by QuantumXenon** [comment]
This is actually working as intended, but the description is confusing - this ability is supposed to heal a small amount of health, but does not fill the soul meter. The description has been updated
