### ISSUE TITLE
Warden Dark Vision

### ISSUE THREAD

**Issue by DarkMage303** [QuantumXenon/origins-plus-plus#345]
**Origin**
Warden

**Power(s)**
Visual Changes

**Balance Suggestion**
Due to the description of the visual changes for the Warden origin saying their eyes are accustomed to pitch darkness, it seems like they are worse at seeing in light, and good in darkness, though i’m finding that both during day and night, as well as underground, it’s always pitch black no matter what. I suggest a night vision effect be added when it’s dark, while keeping the light sensitivity. Version is 1.20.1
Side Question; is there any way to disable the visual effect while keeping the blindness in light, either for the case of a more casual playthrough or for content creation?

**Comment by QuantumXenon** [comment]
I have made changes to address this problem.

As for your question, I have changed it so impactful shaders can now be toggled

**Comment by DarkMage303** [comment]
Awesome! Thank you so much!

**Comment by DarkMage303** [comment]
Just a quick question, is the fix only implemented on newer versions of the game, or is there a keybind in order to toggle the shaders?

**Comment by QuantumXenon** [comment]
The change should work for all Minecraft versions Origins++ is currently compatible with.

There is a keybind to toggle the shader, but I can't remember which it is - maybe F4?

**Comment by DarkMage303** [comment]
Sweet, thank you!
