### ISSUE TITLE
Is there a way to add new origins? or is there a support for this? 

### ISSUE THREAD

**Issue by Viperstarr** [QuantumXenon/origins-plus-plus#347]
I am curious cause I wanted to make more specific origins that are heading more into the medeival directions with origins such as necromancer, sorcerer, druid, barbarian, paladin, assasin and more

is there as support for making new origins?

**Comment by RandomMinecraftGuy** [comment]
i did add rpg origins and it worked

**Comment by Viperstarr** [comment]
link pls

**Comment by QuantumXenon** [comment]
Origins++ is itself and addon to the Origins mod. You can read about making your own [here](https://origins.readthedocs.io/en/latest/) or look for other origins addon mods wherever you download them from
