### ISSUE TITLE
Will not open Origins GUI

### ISSUE THREAD

**Issue by ItzGreenWolf** [QuantumXenon/origins-plus-plus#349]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version-1.20.1
- Mod Loader Version-47.2.21 and (tired 47.2.20)
- Origins Version-origins-forge-1.20.1-1.10.0.5-all.jar
- Origins++ Version-origins-plus-plus-2.2-forge.jar
- Pehkui Version-Pehkui-3.7.12+1.20.1-forge.jar

**Comment by QuantumXenon** [comment]
Merging with #350
