### ISSUE TITLE
Commands for removing and revoking powers don't work as intended

### ISSUE THREAD

**Issue by Johnny78i** [QuantumXenon/origins-plus-plus#359]
**Loader**
Forge

**Versions**
- 1.20.1
- Forge - 47.2.0
- Origins (forge) - 1.20.1 - 1.10.0.7
- Origins++ - 2.2
- Pehkui - 3.8.0+1.20.1

**Issue**
When attempting to remove/revoke a power from an origin (Like the ninetails/firebody power) using the "/power remove" command from the origins mod results in the power being removed, but when logging out and logging back in to the instance the power is back.
For reference, when choosing an origin from the standard origin mod, this issue is not present.

**Comment by wolf-cub-09** [comment]
I have this same issue on fabric version 1.19.2

**Comment by QuantumXenon** [comment]
I don't know if this is the intended functionality of the command, but the `/power` command is part of Origins itself, so whether it is working or not, there isn't really anything I can do to fix it (if it needs it)

**Comment by Xitorr** [comment]
> **Loader** Forge
> 
> **Versions**
> 
> * 1.20.1
> * Forge - 47.2.0
> * Origins (forge) - 1.20.1 - 1.10.0.7
> * Origins++ - 2.2
> * Pehkui - 3.8.0+1.20.1
> 
> **Issue** When attempting to remove/revoke a power from an origin (Like the ninetails/firebody power) using the "/power remove" command from the origins mod results in the power being removed, but when logging out and logging back in to the instance the power is back. For reference, when choosing an origin from the standard origin mod, this issue is not present.

May be a little off/on topic but what source do I use to revoke a power on Origins plus plus? trying to remove heavy from binturong and it requires a manually typed in source, which I don't know how to use.
