### ISSUE TITLE
flea ride on other player bug

### ISSUE THREAD

**Issue by mnmheart** [QuantumXenon/origins-plus-plus#361]
**Loader**
Forge

**Versions**
- Minecraft Version/ 1.20.1
- Mod Loader Version/ 47.2.0
- Origins Version/ 1.20.1
- Origins++ Version/ 1.20.1
- Pehkui Version/ 1.20.1

**Origin**
flea

**Power**
the bug is
ride on other players
it is only on client side
so for any other player you're just standing on the floor

**Notes**
sorry if you already answered this question but I can't seem to find an answer anywhere
thank you

**Comment by QuantumXenon** [comment]
Powers where the player rides on another entity seem to have many issues, so I don't really think there is anything that can be done about it. Origins++ only uses `origins:mount`, so if there is any deeper issue (rather than rendering bugs) it is likely not on my end
