### ISSUE TITLE
Gaia Origin Description Change 

### ISSUE THREAD

**Issue by EanHunt** [QuantumXenon/origins-plus-plus#369]
So I chose the Gaia origin and was a bit lost with what the flowers all did and thought that it was a bit vague. so I spent some time figuring out what all of the flowers did and then edited the origin description to include relevant information. Not a large change but it may help somebody in the future. I am thinking about doing this for some other more vague origin descriptions, but for now just Gaia.

**Gaia**
Impact: ◉◉

You are the mother of all nature, a goddess of earth with a passion for the flowers you've created.

**Floral Teaming:** Your bond with flowers means they give you a unique effect when you are around them (within 4 blocks): Allium (Levitation), Azure Bluet (Glowing), Blue Orchid (Conduit Power), Cornflowers (Night Vision), Dandelions (Haste II), Poppies (Regen II), Lily of the Valley (Absorption), Orange Tulip (Fire Resistance), Oxeye Daisy (Resistance II), Pink Tulip (Jump Boost), Red Tulip (Strength), Sunflower (Hero of The Village), White Tulip (Invisibility), Wither Rose (Strength II), Peonies (3 extra hearts total). Rose Bushes and Lilacs don’t grant any effect, but still function with Floral Superiority.
**Floral Superiority:** You gain Regeneration, Saturation and Speed when around a group of 3 or more flowers. (Does not work with Torch Flowers, Pitcher Plants, Pink Petals or Spore Blossoms).
**Fungal Enemy:** Though you created them, you aren't exactly friends with Fungi. Brown Mushroom (Mining Fatigue), Red Mushroom (Weakness).
**Light As A Flower:** You're as light as a flower giving you permanent slow falling.
**Nature's Danger:** You take more damage from drowning, withering, and burning.
**Photosynthesis:** You can regain hunger from the sun so you can't consume any meat. However, you can eat plants.
**Rose-Sized:** You are naturally smaller in size, being the size of a lovely rose.
**Prickly:** You have natural thorns both allowing you to damage attackers, and scale blocks.
**Thorny Fist:** You have thorns all over your body, and the ones on your fists are designed to have a weak poison that lasts about 1 second. This effect only triggers when punching with no items in hand.

**Comment by QuantumXenon** [comment]
Thanks for this! I am updating the wiki and in-game descriptions to this
