### ISSUE TITLE
Sand Walker origin breaks the game

### ISSUE THREAD

**Issue by Dumpling00** [QuantumXenon/origins-plus-plus#375]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- 1.20.1
- Fabric 0.15.10
- Latest
- Latest
- Latest

**Origin**
What origin is causing the problem?
Sand Walker

**Power**
Just the Origin itself - once chosen, the game stops but you are still able to move. You can break blocks but said blocks don't drop anything. All entities stop. Closing the game becomes impossible unless by force quitting.

**Notes**
An option to disable all skin-recoloring in the config would be nice, instead of manually having to go change the config entries.

**Comment by QuantumXenon** [comment]
Can you please see if you still have this issue, I was not able to reproduce it in testing
