### ISSUE TITLE
Essential and Origins ++ is crashing when friends join my world and vise versa

### ISSUE THREAD

**Issue by Spodsder** [QuantumXenon/origins-plus-plus#381]
**Loader**
Fabric

**Versions**
- Minecraft Version - 1.20.1
- Mod Loader Version - 0.15.11 of Fabric
- Origins Version - 1.12.10
- Origins++ Version - Unsure, file name listed on curseforge is origins-plus-plus-2.2.jar
- Pehkui Version - 3.8.1
- Essential Version - 1.3.2.5?

No origin or power is causing the bug

I get the exit code -1073740791 the second someone joins the server
My driver isn't outdated, and I turn off Razer Synapse through Task Manager

I do have OBS, but it wasn't running, let alone recording, and I don't know if the built in Snipping tool affects it
The same problem happens with all of my friends, someone joins their world and they crash

**Mod List**
![image](https://github.com/QuantumXenon/origins-plus-plus/assets/171396092/97bbb52c-df94-461e-b58c-cf2a1f6347ed)
![image](https://github.com/QuantumXenon/origins-plus-plus/assets/171396092/aeeb9210-d50e-485b-8c54-64f880ee0f02)

The rest of this is the crash report, please let me know anything else you need and I'll try to find it

**Crash Report Recieved**
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-05-31 20:21:26
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_8710$class_9154
	at virtuoel.pehkui.network.ConfigSyncPayload.<clinit>(ConfigSyncPayload.java:13)
	at virtuoel.pehkui.util.ConfigSyncUtils.createConfigSyncPacket(ConfigSyncUtils.java:160)
	at virtuoel.pehkui.util.ConfigSyncUtils.syncConfigs(ConfigSyncUtils.java:145)
	at virtuoel.pehkui.util.ConfigSyncUtils.syncConfigs(ConfigSyncUtils.java:118)
	at virtuoel.pehkui.Pehkui.lambda$onInitialize$0(Pehkui.java:57)
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48)
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:61)
	at net.minecraft.class_3324.handler$zmk000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:4504)
	at net.minecraft.class_3324.method_14570(class_3324.java:195)
	at net.minecraft.class_8610.method_52408(class_8610.java:128)
	at net.minecraft.class_8736.method_53043(class_8736.java:20)
	at net.minecraft.class_8736.method_11054(class_8736.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:738)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_8710$class_9154
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 388454840 bytes (370 MiB) / 2099249152 bytes (2002 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=32.0.15.5585
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32696.82
	Virtual memory used (MB): 19868.10
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 141.49
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20.2
			cloth-config: Cloth Config v12 12.0.109
				cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 13.0.0.6
		comforts: Comforts 7.0.1+1.20.2
			cardinal-components-base: Cardinal Components API (base) 5.3.0
			cardinal-components-entity: Cardinal Components API (entities) 5.3.0
			spectrelib: SpectreLib 0.14.1+1.20.2
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		dynamiclights: Dynamic Lights 1.8.2+mod
		elementa: Elementa 647
		essential: Essential 1.3.2.5+ge4fdbcd438
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		extraorigins: Extra Origins 1.20-13
		fabric-api: Fabric API 0.91.6+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.43+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.6+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.11+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.70+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.28+c8b10480a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.56+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.5+f4be560ba0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.14+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.12+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.47+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.13+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		handcrafted: Handcrafted 3.1.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 16.0.0.2
		minecraft: Minecraft 1.20.2
		modernfix: ModernFix 5.10.1+mc1.20.2
		org_jetbrains_annotations: annotations 23.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		origins: Origins 1.12.10
			apoli: Apoli 2.11.11
				additionalentityattributes: Additional Entity Attributes 1.5.0+1.20.2
				calio: Calio 1.13.3
					org_quiltmc_parsers_gson: gson 0.2.1
					org_quiltmc_parsers_json: json 0.2.1
				playerabilitylib: Pal 1.9.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		origins-plus-plus: Origins++ 2.2
		pehkui: Pehkui 3.8.1+1.14.4-1.20.6
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		resourcefullib: Resourceful Lib 2.2.4
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		universalcraft: UniversalCraft 337
		vigilance: Vigilance 297
		xaerominimap: Xaero's Minimap 24.1.1
		xaeroworldmap: Xaero's World Map 1.38.4
	Server Running: true
	Player Count: 1 / 8; [class_3222['Sp0d3r_Qu33n'/207, l='ServerLevel[New World]', x=-109.90, y=71.00, z=68.40]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.11-1.20.2

**Comment by crazybrain23** [comment]
Pehkui 3.8.1 seems to be problematic.
https://github.com/Virtuoel/Pehkui/issues/518

**Comment by Spodsder** [comment]
Really? I see
Do you happen to know what versions aren't?

**Comment by crazybrain23** [comment]
> Do you happen to know what versions aren't?

3.8.0 works fine

**Comment by Spodsder** [comment]
Alright! Thank you so much!
