### ISSUE TITLE
Felvaxian invisibility doesn't work on mobs

### ISSUE THREAD

**Issue by Amfaro1** [QuantumXenon/origins-plus-plus#384]
Loader
Fabric

Versions
- Minecraft Version 1.20.1
- Mod Loader Version 
- Origins Version 1.10.0
- Origins++ Version 2.2
- Pehkui Version 3.7.8

**Origin** - Felvaxian

**Power** - Invisibility whilst shifting

**Notes** - The invisibility works fine to other players however when shifting around mobs they attack as if I were visible

**Comment by QuantumXenon** [comment]
Merging with #376

**Comment by QuantumXenon** [comment]
This happens because (as far as I know) the armour is only not being rendered for other players, it is still being worn as far as mobs are concerned. See the mentioned issue above for a discussion on what to do about it
