### ISSUE TITLE
calamitous rogue particle spam lagging

### ISSUE THREAD

**Issue by viaviaviaviaviaviaviavia** [QuantumXenon/origins-plus-plus#388]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- Minecraft Version 1.20.1
- Mod Loader Version Fabric 0.15.7
- Origins Version 1.12.1-1.10.0
- Origins++ Version 2.2
- Pehkui Version 3.8.2+1.14.4-1.20.6

**Origin**
calamitous rogue

**Power**
the particles 

**Notes**
A player logged onto the spawn area and became the calamitous rogue origin and the particles are not dissapearing and lagging anyone who comes near them. 
![Uploading 2024-06-21_23.png…]()

**Comment by QuantumXenon** [comment]
The particles are used to mark a point to which they can return to on getting a kill. I have reduced the intensity of the particles to avoid lag as per your comment.
