### ISSUE TITLE
We can't see products of crafting table recipes. We can still retrieve the products, but cannot see them. Blinks and goes away.

### ISSUE THREAD

**Issue by TonyTorzido** [QuantumXenon/origins-plus-plus#39]
**Version**
Fabric - 0.14.7
Origins - 1.18.2 - 1.4.1
Origins-Classes - 1.18.2 - 1.4.1
origins-plus-plus-1.6.2

**Origin**
None

**Power**
None

**Notes**
I am using origins mods on my play through of Valhesia Enchanced Vanilla - 1.18. Normal origins and origins classes works perfect. I then installed Pekhui, and no issues. It wasn't until I installed origins ++ that I encountered the issues. Whenever I try crafting something in a crafting table, the product flashes real quick, then the box (right side) goes blank. You can still make the items. I have tried different versions of every mod and keep getting to the same conclusion. Something in this mod may be interacting with the crafting tables. Any tips?

2x2 crafting works as normal. Here's some pictures:
![image](https://user-images.githubusercontent.com/74726119/176631133-a96ea226-57a8-4ea3-bda5-3337bc6a9a87.png)
![image](https://user-images.githubusercontent.com/74726119/176631203-392f0983-c3ea-4112-9c48-e407f2a7e7b4.png)

EDIT: Seemed to have figured it out. For some reason this mod has complications with fastbench fabric mod.

**Comment by QuantumXenon** [comment]
Glad that you have figured your issue out.
