### ISSUE TITLE
Cannot choose class on server

### ISSUE THREAD

**Issue by Zephosz** [QuantumXenon/origins-plus-plus#393]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version: 1.20.1
- Mod Loader Version: Forge 47.3.4
- Origins Version: 1.10.0.96
- Origins++ Version: 2.2
- Pehkui Version: 3.8.2

**Origin**
N/A

**Power**
N/A

**Notes**
Seems to work for first user after world is built. Haven't tested this extensively but seems to be the case. That user can also run "/origin gui" and get selection as well as use the orb of origins. Other users cannot get origin selection in any way, even after being given op from server console.

Small server running on a Windows 10 VM. Same server has run multiple, much larger modpacks.

**Comment by Zephosz** [comment]
Apologies, it looks like this is a known issue for main Origins (Forge) with 1.20.1. Would still appreciate help if there's any to give.
https://github.com/EdwinMindcraft/origins-architectury/issues/454

**Comment by QuantumXenon** [comment]
It seems to have now been fixed, let me know if you still have any problems
