### ISSUE TITLE
Stargazer infinite weakness

### ISSUE THREAD

**Issue by codenzadev** [QuantumXenon/origins-plus-plus#395]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version 1.20.1
- Mod Loader Version 47.3.0
- Origins Version 1.10.0.9
- Origins++ Version 2.2
- Pehkui Version 3.8.2

**Origin**
Stargazer

**Power**
Starlight

**Notes**
Phantom mode on/off, day/night, starlight mode on/off does not help and weakness stays the same. I have a mod called BetterDays which I used to change the day/night speed by 0.5, but it appears not to interfere with the Speed II and Strength II night effects or the Slowness day effect. Strangely enough, the slowness effect disappears just fine when I enter starlight mode but the weakness effect remains. Unrelated, but what is the little ghost bar to the right near my health bar for?

**Comment by QuantumXenon** [comment]
@codenzadev You still have weakness in starlight mode to stop you from attacking (as per the description for `Starlight Mode`), but the description for `Sunburn` is unclear and makes it sound like it should be removed, so it is working as intended. I will update the description to clarify this.

As for the ghost icon, that is a timer related to the `Starstalker` power (to let you know when you will start to take damage from using it for too long
