### ISSUE TITLE
Deathsworn book

### ISSUE THREAD

**Issue by pikachub2005** [QuantumXenon/origins-plus-plus#398]
**Loader**
Fabric

**Versions**
- Minecraft Version: 1.20.4
- Mod Loader Version: 0.15.11
- Origins Version: 1.13.0-alpha.4
- Origins++ Version: 2.2
- Pehkui Version: 3.8.3

**Origin**
Deathsworn

**Power**
Unleash Potential

**Notes**
Wiki says you'll get a book explaining minion abilities, but you don't

**Comment by QuantumXenon** [comment]
Sorry, this is a mistake - I will update the description
