### ISSUE TITLE
how tf do i heal with automaton

### ISSUE THREAD

**Issue by automaton-enjoyer** [QuantumXenon/origins-plus-plus#399]
**Origin**
Which origin needs the balance?
automaton
**Power(s)**
Which power(s) need(s) to be balanced?
healing
**Balance Suggestion**
Do you have any ideas about how it could be balanced?
telling me how to heal with automaton

**Comment by SamSprink** [comment]
I think it's by design that you don't heal normally, as your health can't go under half a heart. From what I've noticed is that there is still hunger which cannot be refilled because of the inability to eat.

**Comment by QuantumXenon** [comment]
@automaton-enjoyer There was another issues (#404) which meant that the health bar is shown when it is supposed to be hidden, which has now been fixed. As @SamSprink said, health doesn't apply to the automaton as they have the fire/water bars to refill instead
