### ISSUE TITLE
Volcanic Dragon Causing Crashes

### ISSUE THREAD

**Issue by pinkstache** [QuantumXenon/origins-plus-plus#40]
**Version**
Fabric 1.19

**Origin**
Volcanic Dragon

**Power**
None

**Notes**
If anyone tries to select it as their origin, the second they confirm it the server crashes. I've also read from the original mods page that it causes crashes in singleplayer as well

**Comment by QuantumXenon** [comment]
Do you have any other mods installed?

**Comment by QuantumXenon** [comment]
Try updating Origins to 1.6.2 - it seems to fix the issue for me
