### ISSUE TITLE
Balance Fallen Angel : Adds compatibility with the Icarus mod

### ISSUE THREAD

**Issue by Tatou8** [QuantumXenon/origins-plus-plus#408]
**Origin**
Fallen Angel

**Power(s)**
Wings

**Balance Suggestion**
Replace the elytra with the black feather wing of Icarus like the "Medieval Origins Revival" mod with the valkyrie

**Comment by QuantumXenon** [comment]
I don't plan on adding specific mod compatibility like this at the moment, only adding modded items to the tags used by the origins. Thanks for the suggestion though!
