### ISSUE TITLE
Ошибка в происхождениях [Origins lose abilities]

### ISSUE THREAD

**Issue by Ryo26375** [QuantumXenon/origins-plus-plus#409]
**Loader**
Forge

**Versions**
- 1.19.2
- Mod Loader Version
- Origins Version
- максимально возможная
- Pehkui Version

**Origin**
Ошибка во всех происхождениях в многопользовательской игре и одиночной игре. Подключаясь по редмину у друга в мире пропадают некоторые особенности и слабости в происхождениях, так например у Рю пропадают либо все активные способности, либо пропадают крылья. У фантома остаются все способности, кроме слабостей. Это портит баланс игры и все удовольствие

**Comment by QuantumXenon** [comment]
_Google Translate to English (for future reference):_
`Error in all origins in multiplayer and single player. By connecting via redmin to a friend in the world, some features and weaknesses in their origins disappear, for example, Ryu either loses all active abilities or loses his wings. The phantom retains all its abilities except its weaknesses. It ruins the balance of the game and all the fun`

**Comment by QuantumXenon** [comment]
Merging with #379
