### ISSUE TITLE
[White Mage] Crash

### ISSUE THREAD

**Issue by pinkstache** [QuantumXenon/origins-plus-plus#41]
**Version**
Fabric 1.19

**Origin**
White Mage

**Power**
The Ultimate Offensive Attack (Uses the dragon head)

**Notes**
I cannot remember the exact powers name but the UOA with the Dragon Head causes a corrupted entity on the server and the only fix is to roll back the server. (Just in case this is important this happened while our white mage was attacking a Dullahan)

**Comment by QuantumXenon** [comment]
Do you have any other mods installed?

**Comment by pinkstache** [comment]
Yes, there are other mods. Do you need the list of them? I am not exactly clear on how to compile that. Does fabric have a file with all mods listed in it or should I take a picture of what we have or what exactly are the steps for that?

**Comment by QuantumXenon** [comment]
Are you using CurseForge?

**Comment by pinkstache** [comment]
No, we aren't. It's a private modpack our server owner put together.

**Comment by QuantumXenon** [comment]
> Yes, there are other mods. Do you need the list of them? I am not exactly clear on how to compile that. Does fabric have a file with all mods listed in it or should I take a picture of what we have or what exactly are the steps for that?

The best thing to do would probably be to take a picture of all the mods installed in the `[Instance Directory]/mods` folder.

**Comment by pinkstache** [comment]
![Minecraft Mods 1](https://user-images.githubusercontent.com/108646789/177462852-cc42daa9-6365-4db9-b0f7-bb9287d1d558.png)
![Minecraft Mods 2](https://user-images.githubusercontent.com/108646789/177462872-40b17a18-c169-413c-8d7d-c137f03ba130.png)
there hopefully that is correct

**Comment by pinkstache** [comment]
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/9051305/latest.log)
Hopefully that is what you wanted

**Comment by pinkstache** [comment]
Okay she got back to me.
Here is both logs from July 02 when the white mage corrupted the server. We dont know which one you need or if you need both
[2022-07-02-1.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051395/2022-07-02-1.log.gz)
[2022-07-02-2.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051396/2022-07-02-2.log.gz)
And here are all the logs for the 3rd when the volcanic Dragon crashed the server. Once again we aren't sure which one you need and there are a few.
[2022-07-03-3.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051457/2022-07-03-3.log.gz)
[2022-07-03-4.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051458/2022-07-03-4.log.gz)
[2022-07-03-5.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051459/2022-07-03-5.log.gz)
[2022-07-03-6.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051460/2022-07-03-6.log.gz)
[2022-07-03-7.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051461/2022-07-03-7.log.gz)
[2022-07-03-1.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051462/2022-07-03-1.log.gz)
[2022-07-03-2.log.gz](https://github.com/QuantumXenon/origins-plus-plus/files/9051463/2022-07-03-2.log.gz)

**Comment by QuantumXenon** [comment]
Thanks! I'll have a look and see if I can figure out what's going on.

**Comment by QuantumXenon** [comment]
_-> Please make a backup before doing this._
Try updating Origins to 1.6.2, it fixed a similar problem for me.
I have also made minor changes to the Volcanic Dragon and White Mage, but the Origins update should fix the crashes/corruptions

**Comment by pinkstache** [comment]
We have updated both origins and origins ++ and white mage and volcanic dragon are no longer crashing the server. Also quite a few little bugs have also been fixed such as broodmothers webs can now be destroyed, amongst others. Thank you.

**Comment by QuantumXenon** [comment]
Excellent, I’m glad that everything is sorted
