### ISSUE TITLE
Light Mage - Invisible Armor Stands Persist Indefinitely + More

### ISSUE THREAD

**Issue by DCC-Matrix** [QuantumXenon/origins-plus-plus#411]
**Loader**
Fabric

**Versions**
- Minecraft Version: 1.20.1
- Mod Loader Version: 0.16.2
- Origins-1.20.1-1.10.0
- origins-plus-plus-2.2
- Pehkui-3.8.3+1.14.4-1.21

**Origin**
Light Mage

**Power**
Pocket Dimension

**Notes**
An invisible armor stand is created at your location when you go to your pocket dimension. When you exit your pocket dimension, you are teleported to the armor stand. The armor stand is never automatically killed by the game. It will stay at its location unless it is killed by commands. The only way of getting rid of them that I have discovered is by placing armor on it, taking the armor off of it, then using the command `/data get entity [autofill the only super long nonsense name with tab (this is the armor stand)]`, then using the command `/kill [same super long nonsense name]`

Edit: I just figured out that I can use the command `/kill @e[distance=0..3,type=minecraft:armor_stand,tag=back]` to kill all invisible armor stands within 3 blocks of me. For some reason, this command doesn't appear to automatically run when returning from the pocket dimension.

Edit 2: I found out that pressing the `return from pocket dimension` key after returning from the pocket dimension causes the armor stand to die.

Edit 3: The game does not remove the tag `tppocket` from other players when they return from the pocket dimension.

**Comment by bolledyr123** [comment]
how did u fix it?

**Comment by DCC-Matrix** [comment]
> how did u fix it?

I did not.
