### ISSUE TITLE
technomancer abilities wont activate

### ISSUE THREAD

**Issue by indominusbat** [QuantumXenon/origins-plus-plus#412]
**Loader**
fabric

**Versions**
- 1.20.1
- fabric
- 1.10
- 2.2
- 3.8.3

**Origin**
technomancer

**Power**
all of them. the techomancer abilities dont seem to work.

**Notes**
i get the items and my mana will charge its just the items cant be used it wont activate the abilities

**Comment by QuantumXenon** [comment]
I was unable to reproduce these results with testing - just to confirm, when you have mana, were you holding the staff in your offhand and using (default: `Right Button`) with one of the items given to you?

**Comment by indominusbat** [comment]
> I was unable to reproduce these results with testing - just to confirm, when you have mana, were you holding the staff in your offhand and using (default: `Right Button`) with one of the items given to you?
yes this is correct i had them in my offhand and i had full mana. the mana charged. i had the items they just wouldn't activate when i pressed the button.

**Comment by indominusbat** [comment]
yha it works without any other mods
sorry for taking up your time.
