### ISSUE TITLE
Forge Server not working

### ISSUE THREAD

**Issue by Lacox** [QuantumXenon/origins-plus-plus#43]
So I saw this was a fixed problem, but on my forge server, I still cannot use Origins ++ since it uses too many bytes. I am running the Forge version of the mod (1.6.2) on Forge 40.1.16, and XL Packet is fabric exclusive to my knowledge. If there is any way to fix this problem, help would be much appreciated.

Thanks!

**Comment by KomainTodd** [comment]
Also having this problem, I think its to do with the craftsman origin because I saw someone have this problem with the original datapack :/

**Comment by KomainTodd** [comment]
Payload may not be larger than 1048576 bytes was the error I was getting

**Comment by Lacox** [comment]
Around the same error as me.

**Comment by KomainTodd** [comment]
So I found that using the mod Connectivity it fixes the byte error and loads like normal, hope that helps

**Comment by QuantumXenon** [comment]
@Lacox Did connectivity work for you?
