### ISSUE TITLE
Secondary Origin Ability Shows Not Bound Despite Being Bound; Button Does Nothing

### ISSUE THREAD

**Issue by storeystory** [QuantumXenon/origins-plus-plus#434]
**Loader**
_Forge_ or Fabric?

**Versions**
- Minecraft Version
1.20.1
- Mod Loader Version
47.3.10
- Origins Version
1.20.1-1.1.0.0.9
- Origins++ Version
2.2-forge
- Pehkui Version
3.8.2+1.20.1-forge

**Origin**
What origin is causing the problem?
Felvaxian

**Power**
What power is causing the problem?
Scavenger Pouch

**Notes**
Include any other information that might be useful here

In the Origin page, the symbol beside the Scavenger Pouch section title says that the key to open the scavenger pouch is not bound, even though Active Power (Secondary) is bound with no conflicts. Pressing the button, no matter what button it is, doesn't do anything.

**Comment by QuantumXenon** [comment]
Sorry for the delayed response - this has been fixed since the last release but I haven't put out a new version with it
