### ISSUE TITLE
Deathsworn not dropping Petrified Hearts

### ISSUE THREAD

**Issue by Farfalleus** [QuantumXenon/origins-plus-plus#442]
**Loader**
Forge

**Versions**
- Minecraft 1.19.2
- Forge 1.19.2 - 43.4.0
- Origins Version 1.19.2 - 1.7.1.7
- Origins++ Version 2.2
- Pehkui Version 3.8.2

**Origin**
Deathsworn

**Power**
Petrified Hearts Aren't dropping!! Please help!

**Notes**
I'm using an aternos server.
Is dropping the petrified hearts just really rare?
I also tried to look up the hearts in the creative search menu and they weren't there. I also tried typing "/give @p heart" and "/give @p petrified" and nothing came up.

**Comment by falloffladder** [comment]
im having the same problem! i hope they can fix it

**Comment by QuantumXenon** [comment]
This is a known issue with Origins (Forge) itself and has been reported to the developers, so there isn't really anything I can do about it at the moment
