### ISSUE TITLE
deathsworn not droping hearts?

### ISSUE THREAD

**Issue by falloffladder** [QuantumXenon/origins-plus-plus#444]
curse forge
forge

**Versions**
- Minecraft Version 1.20.1
- Mod Loader Version 47.3.0
- Origins Version 1.10.0.9
- Origins++ Version 2.2
- Pehkui Version 3.8.2

**Origin**
What origin is causing the problem?
Deathsworn
**Power**
What power is causing the problem?
Heart-Stopping
mobs wont drop any hearts
**Notes**
Include any other information that might be useful here
i'm playing with essential in a multiplayer world if that changes anything

**Comment by QuantumXenon** [comment]
This is a known issue with Origins (Forge) itself and has been reported to the developers, so there isn't really anything I can do about it at the moment
