### ISSUE TITLE
Wither Skeletian incompatible with LudoCrypt's Corners Mod

### ISSUE THREAD

**Issue by Youhadabadday** [QuantumXenon/origins-plus-plus#46]
**Version**
Fabric 0.14.8

**Origin**
Wither Skeletian

**Power**
Unnatural Height

**Notes**
I am unable to use the painting portals from LudoCrypt's "The Corners" mod as a Wither Skeletian because of how the changed height is handled. According to the developer, the paintings work based on the position of the eyes in comparison to the painting, and if it's lined up right, the player will teleport to the dimensions added in the mod. However, the Wither Skeletian's added height makes him unable to fulfill this requirement. Crouching should fix it, but apparentally the height of the eyes isn't changed when crouched.

**Comment by QuantumXenon** [comment]
Ok, thanks for letting me know. As far as I know there isn’t anything I can do about it because eye height will be changed by Pehkui which is used by Origins++
