### ISSUE TITLE
[Black Mage] Hidden Spells

### ISSUE THREAD

**Issue by MysticOwll** [QuantumXenon/origins-plus-plus#47]
**Version**
Fabric 1.19

**Origin**
Black Mage

**Power**
11th Hidden spell: Explosion, 12th hidden spell: Shatter, Ultimate abilities: Ultimate explosion, and Ultimate nightmare trip

**Notes**
these 4 spells just dont work, i'm not sure why but everything else works perfectly fine. These dont even use mana too, they just dont do anything

**Comment by QuantumXenon** [comment]
I also have the same issue, but I'm not sure why they would not be working

**Comment by snorlaxpanda21** [comment]
im not sure if you will see this but is this fixed or will it still not work, or is there an updated version i need to use?

**Comment by QuantumXenon** [comment]
This has not yet been fixed- I’m working on it though

**Comment by snorlaxpanda21** [comment]
Sorry I saw post at 25 days and didn't see your recent comment my bad
