### ISSUE TITLE
Origins++ causes java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes on version 1.18.2

### ISSUE THREAD

**Issue by empty-window** [QuantumXenon/origins-plus-plus#48]
I'm trying to run this origins addon with other origins addons. I tested it under different situations because I wanted to know if it was incompatible with other addons. I found that even running on its own (with origins and pekui) loading a single player world produces java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes.

The entire log is pasted below.
[here.log](https://github.com/QuantumXenon/origins-plus-plus/files/9177787/here.log)

**Comment by QuantumXenon** [comment]
Try downloading XL Packets
