### ISSUE TITLE
Internal Exception: java.util.ConcurrentModificationException.

### ISSUE THREAD

**Issue by Gintoki000** [QuantumXenon/origins-plus-plus#49]
**Version**
Forge
version: 1.18.2

**Origin**
The origin that is affected by the problem
Adds this expansion mod (origins-plus-plus) when playing with the Origins (Forge) mod. When creating a new world or entering a previously created world, there is a chance of displaying garbled characters "Internal Exception: java.util.ConcurrentModificationException".

Even when entering the world to play the game, clicking to return to the title interface will have a chance to cause the game to crash directly.

**Notes**
Only Origins (Forge) and its pre-mods and this mod (origins-plus-plus) are added to the mods folder.
I don't know which file is a valid bug report, so I uploaded them both.

[debug.log](https://github.com/QuantumXenon/origins-plus-plus/files/9182531/debug.log)
[hs_err_pid8784.log](https://github.com/QuantumXenon/origins-plus-plus/files/9182532/hs_err_pid8784.log)
[latest.log](https://github.com/QuantumXenon/origins-plus-plus/files/9182533/latest.log)

**Comment by QuantumXenon** [comment]
@Gintoki000 I have replicated your mod setup, and encounter the same issue. However, if I update Forge to 40.1.73, I no longer experience the issue.
