### ISSUE TITLE
Wizard Wither skull ability not working

### ISSUE THREAD

**Issue by Tomziloy** [QuantumXenon/origins-plus-plus#50]
How do you bind the third keybind? I'm using the wizard origin and I don't know how to use the wither skull shooting ability as in the keybinds there is no 3rd power... I have tried the origins keybind mod but the third keybind did not bind to it and nor did any of the others. PLEASE HELP!

**Comment by QuantumXenon** [comment]
For a bound more than secondary, try Load/Save hotbar, and Show Spectator Outlines
