### ISSUE TITLE
Ticking Player Issue.

### ISSUE THREAD

**Issue by aanthonyssandoval1999** [QuantumXenon/origins-plus-plus#53]
**Version**
Forge/Fabric and the version number
            Forge Version 40.1.68 Version 1.6.2**Origin**
The origin that is affected by the problem
           All Origins
**Power**
The name of the power that is affected by the problem
              N/A
**Notes**
Any other information that might be useful
             As soon as I select a Origin and load into the world I immediately Freeze and the game crashes due to Ticking Player error. I have tried using different versions of the Origins++ but have had no luck. I absolutely Love this mod and cannot play Minecraft without it. Please help me fix this.

**Comment by QuantumXenon** [comment]
What version of Origins are you using?

**Comment by aanthonyssandoval1999** [comment]
> 

1.18.2 Forge version 40.1.68  and version 1.6.2

**Comment by QuantumXenon** [comment]
Also. what version of Pehkui are you using?

**Comment by QuantumXenon** [comment]
@aanthonyssandoval1999 I no longer experience the issue when I update Pehkui to 3.4.0 and Forge to 40.1.73
