### ISSUE TITLE
Ninetails' Hydrophobia is too strong

### ISSUE THREAD

**Issue by DuhDoesNothing** [QuantumXenon/origins-plus-plus#54]
**Origin**
Ninetails
**Balance Request**
the hydrophobia ability's damage
**Suggestion (If Possible)**
in its current state, the hydrophobia ability does 4 hearts of damage per water tick
i feel like it should be lowered to 1-2 hearts, since 4 hearts is basically instant death in water

**Comment by QuantumXenon** [comment]
Ok, I’ll change that
