### ISSUE TITLE
Fabric Crash

### ISSUE THREAD

**Issue by sabreathena** [QuantumXenon/origins-plus-plus#55]
**Version**
Forge/Fabric and the version number

**Origin**
The origin that is affected by the problem

**Power**
The name of the power that is affected by the problem

**Notes**
Any other information that might be useful

**Comment by QuantumXenon** [comment]
Do you have Origins and Pehkui installed?

**Comment by QuantumXenon** [comment]
And what is the error message in the logs?

**Comment by bogthefrog** [comment]
I have a similar error and my bug message is The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'

**Comment by QuantumXenon** [comment]
@bogthefrog What version of Origins are you using?

**Comment by bogthefrog** [comment]
Origins 1.6.2 I believe

**Comment by QuantumXenon** [comment]
Could you provide a log? I can't replicate the issue

**Comment by QuantumXenon** [comment]
Merging with #61
