### ISSUE TITLE
Internal exeption: java.util.concurrentmodificationexeption

### ISSUE THREAD

**Issue by BONEWEEVIL1** [QuantumXenon/origins-plus-plus#56]
**Version**
Forge 1.6.2 

Internal exeption: java.util.concurrentmodificationexeption keeps poping up when i try and load inot my server with orgins plus plus

**Comment by QuantumXenon** [comment]
What version of Origins are you using?

**Comment by BONEWEEVIL1** [comment]
orgin plus plsu 1.6.2 on forge

**Comment by QuantumXenon** [comment]
What about the actual Origins mod?

**Comment by BONEWEEVIL1** [comment]
origins fore 1.18.2 v1.2.0

**Comment by QuantumXenon** [comment]
Merging this with #49
