### ISSUE TITLE
Error: requires apoli 1.18.2-1.4.1.4 or above

### ISSUE THREAD

**Issue by JudyJiggle** [QuantumXenon/origins-plus-plus#57]
**Version**
Forge-41.1.0

**Origin**
Missing mandatory dependencies: apoli

**Power**
Idk what this means lol

**Notes**
I investigated as hard as I could to solve this problem. Apoli doesn't work. I am trying to install Origins++, but when I load in, it says I require ¨apoli 1.18.2-1.4.1.4 or above¨. Weird, because the version of Java is 1.19. So when I tried either 1.19 or 1.18.2 version of the mod, it didn't work. It's as if it's not detecting them, or the one that Curseforge wants to download is not trackable.

**Comment by QuantumXenon** [comment]
Try this one: https://www.curseforge.com/minecraft/mc-mods/origins-forge/files/3898807
