### ISSUE TITLE
[Craftsman] Respawning

### ISSUE THREAD

**Issue by KVBAMusic** [QuantumXenon/origins-plus-plus#58]
**Version**
Fabric 0.14.8, Minecraft 1.19, Origins 1.6.2, Origins++ 1.6.2

**Origin**
Craftsman

**Notes**
After dying of anything as a craftsman, you cannot respawn
The "You died" screen shows, but everytime i clicked "Respawn" button, it grayed out for a while and did not respawn me

this could be a conflict with another mod, but only craftsman is affected by it

**Comment by KVBAMusic** [comment]
forgot to mention, my version of Minecraft is 1.19

**Comment by QuantumXenon** [comment]
This could be an issue with the actual Origins mod, but I'm not 100% sure.

**Comment by QuantumXenon** [comment]
I've temporarily disabled this power until I manage to fix it to prevent any issues
