### ISSUE TITLE
All Keybinds are set to Primary

### ISSUE THREAD

**Issue by ParkyTheSparky** [QuantumXenon/origins-plus-plus#59]
**Version**
Forge/Fabric and the version number
1.5.3

**Origin**
The origin that is affected by the problem
All origins with multiple abilities

**Power**
The name of the power that is affected by the problem
e.g. Devine Architect: Float, Universal Blast, Phase. (Multiple origins do this.)

**Notes**
Any other information that might be useful
They all say "Active ability, use with [g]"

I believe the cause of this is the "key" string. As some of them have "key": "key......." instead of
"key": {
"key": "key......."
}

**Comment by QuantumXenon** [comment]
I don't seem to have this problem. Can you try updating to the latest version of Origins (if not already) and Origins++ and see if you still experience it?

**Comment by QuantumXenon** [comment]
@ParkyTheSparky Are you using Forge or Fabric?

**Comment by ParkyTheSparky** [comment]
I am using forge. Also, I am on the latest version for 1.18.2

**Comment by QuantumXenon** [comment]
There is an issue with the Origins (Forge) mod that make the keys not work correctly. I have already let the developer know and they said that they were aware of the issue

**Comment by ParkyTheSparky** [comment]
Awesome! I'm glad it wasn't just me haha.

**Comment by QuantumXenon** [comment]
@ParkyTheSparky Try updating Origins (Forge) to 1.5.0.6 - it fixed the issue for me.
