### ISSUE TITLE
Internal exeption: java.util.concurrentmodificationexeption

### ISSUE THREAD

**Issue by mmiller9196** [QuantumXenon/origins-plus-plus#60]
My version is 1.18.2 (FORGE) and the mod is V1.6.2 I need some help with solving this issue, could someone help me?

**Comment by QuantumXenon** [comment]
What version of Pehkui are you using? - I can replicate this issue, but only with Pehkui 3.4.0

**Comment by QuantumXenon** [comment]
Merging with #49

**Comment by mmiller9196** [comment]
@QuantumXenon lifesaver :)
