### ISSUE TITLE
Abilities have with same key

### ISSUE THREAD

**Issue by TehBooris** [QuantumXenon/origins-plus-plus#62]
**Version**
Forge/Fabric and the version number
Fabric, 1.6.2
**Origin**
The origin that is affected by the problem
There's a few I've ran into that have done this I believe, I know the Warden does.
**Power**
The name of the power that is affected by the problem
Echolocation and Phase

**Comment by QuantumXenon** [comment]
The Echolocation and Phase accidentally were made to have the same key. This will be fixed in the next version
