### ISSUE TITLE
[Binturong] Ride

### ISSUE THREAD

**Issue by rainerie** [QuantumXenon/origins-plus-plus#63]
**Version**
1.19

**Origin**
Binturong

**Power**
Riding

**Notes**
When you ride a player, it crashes the server and doesn't allow the rider to play with the person they rode. 

Worded slightly weird, but y'know.

**Comment by QuantumXenon** [comment]
I understand what you mean, but I won't have a way to test this for some time

**Comment by QuantumXenon** [comment]
I tested it, but I didn't encounter the issue. Are you still experiencing it?

**Comment by QuantumXenon** [comment]
@rainerie Do you still have the issue with v1.7.1?

**Comment by rainerie** [comment]
I do not! Thank you. :)

**Comment by rainerie** [comment]
Hii!! I switched servers, so the issue fixed itself, but it might've just been an Aternos issue? Not sure why else it would just fix itself.
