### ISSUE TITLE
[Deathsworn] Petrified Hearts Don't Drop

### ISSUE THREAD

**Issue by Thrity452** [QuantumXenon/origins-plus-plus#65]
**Version**
Forge 40.1.52

**Origin**
Deathsworn

**Power**
Heart Stopping and Submit!

**Notes**
It does not matter which mobs I kill and how many, the petrified hearts don't drop. 

I'm able to see the ray, but it doesn't damage any entity.

I'm unable to accumulate Soul Energy neither by killing mobs or during the night.

**Comment by QuantumXenon** [comment]
I don't know what causes this, but I think it is an issue with Origins (Forge)
