### ISSUE TITLE
Solutions to Frequent Issues

### ISSUE THREAD

**Issue by QuantumXenon** [QuantumXenon/origins-plus-plus#67]
_This is a collection of solutions to some of the more frequent issues. If any of the solutions don't work, comment below and I will try to help you._

**Payload May Not be Larger Than [...] Bytes**
-> Install [XL Packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) (for Fabric) or [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) (for Forge)

**All Keybinds are set to Primary**
-> Install Origins (Forge) 1.5.0.6+

**Exception in Server Tick Loop**
-> Origins itself is causing this issue (https://github.com/apace100/origins-fabric/issues/581#issuecomment-1201637804)

**Internal Exception: java.util.ConcurrentModificationException**
-> Update Forge to the most recent version

**Ticking Player**
- Update Forge/Origins/Pehkui to the most recent version

**Comment by Xplodin** [comment]
getting concurrentmodificationexception with latest 1.18.2 forge 40.1.74 but not on 40.1.73

**Comment by SnowfallLP** [comment]
I am still getting Invalid Playerr Data even after installing all of the Mods listed Above.

**Comment by QuantumXenon** [comment]
@SnowfallLP Are you using Fabric or  Forge (and what Minecraft version)?

**Comment by SnowfallLP** [comment]
I am using 1.19.2 Forge

**Comment by QuantumXenon** [comment]
Try deleting the config file and seeing if that helps

**Comment by SnowfallLP** [comment]
What is it called? I can only find a File named "origins-common.toml" and if i delete that i still get the Error.

**Comment by QuantumXenon** [comment]
That’s the config file. I don’t know what else you can do to fix the issue of you’ve done all that.

As far as I can tell, the error is caused by the way Origins (Forge) handles addons, so if packet expanding mods don’t work, I don’t know what else to suggest

**Comment by TaterDave** [comment]
Interesting, I am having inconsistent results with using each of the packet mods listed above and deleting the config. I’m leaning towards an other than Origins++ mod conflicting with the packet limit mods or a problem on 1.19.2 in general when you are running an excessive amount of mods like the ATM8 modpack . 

Origins++ works completely fine when alone (with all dependencies on 1.19.2), so these issues seem to be coming from an unknown source.
