### ISSUE TITLE
Respawn Resetting Issues

### ISSUE THREAD

**Issue by Morples** [QuantumXenon/origins-plus-plus#69]
**Loader**
Forge

**Versions**
- Minecraft Version - 1.19
- Mod Loader Version -41.1.0
- Origins Version - 1.5.0.4
- Origins++ Version - 1.7 
- Pehkui Version-3.4.1

**Origin**
Whenever I die, the gui overlay for the cooldowns and such for only origins++ origins no longer work. Damage taken and damage in water still stays (maybe a few others), but abilities and the passive enchantment don't stay until I re-give myself the origin.

**Comment by QuantumXenon** [comment]
Does updating Origins (Forge) help at all?

**Comment by QuantumXenon** [comment]
@Morples I can't seem to replicate this issue. if you still have it after updating Origins, please re-open this issue
