### ISSUE TITLE
[Ninetails] Hydrophobia

### ISSUE THREAD

**Issue by AliCCfire** [QuantumXenon/origins-plus-plus#71]
**Origin**
Which origin needs the balance?
* Ninetails 

**Power(s)**
Which power(s) need(s) to be balanced?
* Hydrophobia. water damage disproportionally high with rain

**Balance Suggestion**
Do you have any ideas about how it could be balanced?
* much like fire doesn't immediately burn out with rain and blazes take reduced damage from it compared to water and snow, i'd like to suggest halving the damage dealt by rain (or at least scale it much like vanilla fire damage, as now the hydrophobia deals precisely as much damage as lava in the base game.

**Comment by QuantumXenon** [comment]
The damage is now in line with the Blazeborn from the base mod
