### ISSUE TITLE
Connection to single-player worlds?

### ISSUE THREAD

**Issue by RensinEpidemic** [QuantumXenon/origins-plus-plus#73]
**Loader**
Forge or Fabric?

**Versions**
- Minecraft Version
- Mod Loader Version
- Origins Version
- Origins++ Version
- Pehkui Version

**Origin**
What origin is causing the problem?

**Power**
What power is causing the problem?

**Notes**
Any other information that might be useful
My game is "not connecting" to a server that doesn't exist, I am trying to play on my single player worlds and it's somehow disconnecting me when there is no server to connect to.
I am using the full version of Minecraft

**Comment by CrazyGinger42** [comment]
I use Curse Forge and only Origins++ seems to have a problem. I have Pehkui installed and its in the correct version (1.19.2 MC // 43.1.3 Forge) and all other origins load up great. I had Origins++ working the day before yesterday but then all of a sudden it was saying I couldn't connect to a server when making a single player world (After creating a sigle player world it would say "can't connect to server and spit me out in the Multiplayer server list screen).

**Comment by QuantumXenon** [comment]
I had a similar issue. The fix I used was XL Packets for Forge (I know there isn’t a 1.19 version - I manually updated it myself). I have submitted the updated version to the author's GitHub page, so hopefully it will be available soon (on CurseForge) for everyone.

**Comment by QuantumXenon** [comment]
This should be fixed in the next version

**Comment by QuantumXenon** [comment]
@CrazyGinger42 @RensinEpidemic Is this now working in the latest version?
