### ISSUE TITLE
javafml:43 or above?

### ISSUE THREAD

**Issue by mrrongy** [QuantumXenon/origins-plus-plus#76]
**Loader**
Forge - 40.1.80

**Versions**
- Minecraft 1.18.2
- Mod Loader - Overwolf, Curse Forge
- Origins 1.18.2-1.4.1.4-unified.jar
- Origins++ 1.7.1.jar
- Pehkui Version 3.4.2+1.18.2-forge.jar

**Origin**
What origin is causing the problem?
Origin++ language reader?

**Notes**
Any other information that might be useful
my issue is with a Jar reader, when i play it one MC version 1.18.2 it tells me that Origin++ needs a language provider javafml:43 or above, i dont know how to fix that. im using Overwolf, Curse Forge create a profile, to make a mod pack

**Comment by Xplodin** [comment]
how does one get past this without downgrading the mod?

**Comment by QuantumXenon** [comment]
Version 43 and above means 1.19.2+. I have restricted it because there was a severe bug where keybinds didn't work properly that was only fixed in a version of Origins (Forge) for 1.19.2.
