### ISSUE TITLE
[Blazian] Nether Ally + Blazing Leap

### ISSUE THREAD

**Issue by Hisui02** [QuantumXenon/origins-plus-plus#77]
That's it, I'm playing on a Forge Server, with some friends and two of them are using the origin, the told me it wasn't working properly and iI changed my origin to test it and worked for me. After some testing we discovered it only works if you are a server operator.

origins plus plus version 1.7.1

**Comment by QuantumXenon** [comment]
- Slow falling not applying
- Nether mobs targeting player

**Comment by QuantumXenon** [comment]
In `server.properties`, what is `function-permission-level` set to?

**Comment by Hisui02** [comment]
It's set to 2, I guess it's the default I didn't touch it, should I?

**Comment by QuantumXenon** [comment]
I'm pretty sure that mob targeting is broken on Forge. If that's the case, there isn't anything I can do. As for the slow falling, I don't seem to have that issue - I'll look some more though
