### ISSUE TITLE
Forge 41.3.25 1.19.2 is getting invalid data error

### ISSUE THREAD

**Issue by Thisguyneedshelp** [QuantumXenon/origins-plus-plus#82]
Heres the logs https://mclo.gs/23xVVOq

**Comment by QuantumXenon** [comment]
@Thisguyneedshelp Try installing this: https://www.curseforge.com/minecraft/mc-mods/xl-packets-renewed

**Comment by Thisguyneedshelp** [comment]
it works thank you
