### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by SugarDaddii** [QuantumXenon/origins-plus-plus#85]
**Loader**
Forge

**Versions**
- Minecraft Version:1.19.2
- Mod Loader Version: 43.1.27
- Origins Version 1.5.0.6
- Origins++ Version 1.7.2
- Pehkui Version 3.4.2

**Origin**
Nothing
**Power**
Nothing

ERROR
If i create a world and join first time SOMETIMES its working but after exit the world and come back it always disconnect me and says invalid player data ... after switching off your mod and joining again its working again

**Comment by QuantumXenon** [comment]
@SugarDaddii Does installing https://www.curseforge.com/minecraft/mc-mods/xl-packets-renewed help?

**Comment by SugarDaddii** [comment]
When i installing this Xl Mod i cant pick my origin any more. game will start without this little window when i start the world

**Comment by SugarDaddii** [comment]
Thats now fixed with XL Packet ... but clients need to have this installed
