### ISSUE TITLE
[Lepus] Dash

### ISSUE THREAD

**Issue by SugarDaddii** [QuantumXenon/origins-plus-plus#86]
**Loader**
Forge

**Versions**
- 1.19.2
- 43.1.32
- 1.5.0.6
- 1.7.2
- 3,4,2
**Origin**
What origin is causing the problem?
- Lepus 
**Power**
What power is causing the problem?
- Leap
**Notes**
Any other information that might be useful

**Comment by QuantumXenon** [comment]
It seems to be working for me. What issue(s) are you experiencing?

**Comment by SugarDaddii** [comment]
when i push the activate key the dash line on the bottom will activate green but nothing will happen...i also install only origin + origin ++ and there is also the error where the dash dont activate correctly
