### ISSUE TITLE
invalid player data

### ISSUE THREAD

**Issue by PunctalBoat203** [QuantumXenon/origins-plus-plus#90]
**Loader**
 Fabric

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version 0.14.9
- Origins Version 1.19.2-1.7.10
- Origins++ Version1.19.2-1.7.2
- Pehkui Version1.19.2-3.5.0

**Notes**
i have tryed the xl packets and every thing but i keep getting  smacked with invalid player data only when i have loaded origins plus plus both singleplayer and mutiplayer i can't seem 2 find why it's doing it

**Comment by QuantumXenon** [comment]
Try installing XL Packets (Fabric): https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric
The latest version (while only marked for 1.17), should work for 1.19.2

**Comment by QuantumXenon** [comment]
If that hasn't solved it, please reopen this issue
