### ISSUE TITLE
Can't read the Origin's abilities

### ISSUE THREAD

**Issue by Enejuto** [QuantumXenon/origins-plus-plus#94]
**Loader**
Forge

**Versions**
- 1.19.2
- Forge 43.1.1
- 1.19.2
- 1.19.2
- 1.19.2

**Origin**
All origins

**Power**
Can't read the Origin's abilities in the gui

**Notes**
On a server that I run, other people cannot read the abilities of all the Origins, only me.

**Comment by QuantumXenon** [comment]
Do you have any other mods installed?

**Comment by MiniNox** [comment]
Yes, we have a few other mods installed, do I need to provide a list?

**Comment by QuantumXenon** [comment]
Yes, please

**Comment by MiniNox** [comment]
Modlist: (Server-Side)
Alex's Mobs | https://www.curseforge.com/minecraft/mc-mods/alexs-mobs
Appleskin | https://www.curseforge.com/minecraft/mc-mods/appleskin
Biome's O' Plenty | https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
Caelus | https://www.curseforge.com/minecraft/mc-mods/caelus
Citadel | https://www.curseforge.com/minecraft/mc-mods/citadel
Create | https://www.curseforge.com/minecraft/mc-mods/create
Origins (Forge) | https://www.curseforge.com/minecraft/mc-mods/origins-forge
Origin's Plus Plus (This mod)
Pehkui | https://www.curseforge.com/minecraft/mc-mods/pehkui
Terrablender | https://www.curseforge.com/minecraft/mc-mods/terrablender
Simple Voice Chat (Forge) | https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat
XL Packet's Renewed | https://www.curseforge.com/minecraft/mc-mods/xl-packets-renewed

That's all the server side mods, I have encouraged players to install Optifine aswell.

**Comment by QuantumXenon** [comment]
It could be XL Packet's Renewed - I've noticed that sometimes it seems to skip the Origins GUI. While it's not ideal, you could use something like [Starter Kit](https://www.curseforge.com/minecraft/mc-mods/starter-kit) to give everyone an Orb of Origin the first time they join as a temporary fix

**Comment by Enejuto** [comment]
Good idea, I'll try first by taking out the XL Packet's, I'll give you any updates later

**Comment by QuantumXenon** [comment]
Please reopen this if your issue is not solved.
