### ISSUE TITLE
Bug on trying to enter my world

### ISSUE THREAD

**Issue by paodalho** [QuantumXenon/origins-plus-plus#98]
**Loader**
Forge or Fabric? forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version 43.1.25
- Origins Version 1.5.0.6
- Origins++ Version 1.7.2
- Pehkui Version 3.4.2

when trying to enter a previously made world it crashes saying i have invalid player data and sends me back to the multiplayer servers page, this happens trying to enter a SINGLEPLAYER world, i tried everything but it keeps happening, i also tested all of the mods im using and only when turning off origins ++ it stops happening.
![imagem_2022-11-01_024142835](https://user-images.githubusercontent.com/117144867/199166740-73426955-427c-4301-b2be-fb4419deffe1.png)

**Comment by QuantumXenon** [comment]
Try using [XL Packets Renewed](https://www.curseforge.com/minecraft/mc-mods/xl-packets-renewed)

**Comment by paodalho** [comment]
it did solve the first problem! but now i have trouble trying to enter my
friends LAN world, it says this:

i first thought this was a too much mods problem, but when origins++ is
disabled it stops happening, we also are using only 40 mods
